  function renderEnemies(){const rows=filtered("enemies",["name","filename","id","scanDescription"]),sample=state.data.enemies.rows.find(row=>row.available),columns=[{key:"id",label:"ID"},{key:"name",label:"Enemy",render:row=>recordHoverLabel("enemies",row,enemyDisplayName(row.name))},{key:"scanDescription",label:"Scan description",pinned:false},...(sample?.fields||[]).map(field=>({key:`field:${field.field}`,label:field.label,pinned:false,numeric:field.control!=="boolean"&&field.lookup?.type!=="enum",sortValue:row=>row.fields.find(value=>value.field===field.field)?.value??"",render:row=>row.fields.find(value=>value.field===field.field)?.value??""}))];showPaged("enemies",rows,columns,enemyDetail,"74px minmax(180px,1fr)",{leadingPanel:enemyLeadingPanel,minLeading:340,defaultLeadingWidth:30,minLeft:260,minRight:430})}

  function encounterName(row){const names=row.slots.filter(slot=>slot.enabled).map(slot=>enemyDisplayName(slot.enemyName)),summary=[...new Set(names)].slice(0,3).join(", ");return summary||`Encounter ${row.id}`}
  function encounterReferences(id,read){return state.references.map(reference=>({name:reference.name,shortName:reference.shortName,value:read(rowOf(state.referenceData[reference.id],"encounters",id))})).filter(entry=>entry.value!==undefined)}
  function encounterSource(control,row,read,apply,format=value=>String(value)){return sourceControl(control,()=>read(row),read(rowOf(state.vanilla,"encounters",row.id)),encounterReferences(row.id,read),apply,format,{internal:control?.matches?.('input[type="number"],input[inputmode="decimal"]')===true})}
  function encounterLevelRule(raw){raw=Number(raw);if(raw===252)return{mode:"ultimecia",value:1};if(raw>=1&&raw<=100)return{mode:"fixed",value:raw};if(raw>=101&&raw<=200)return{mode:"maximum",value:raw-100};return{mode:"special",value:1}}
  function encounterLevelControl(slot){
    const rule=encounterLevelRule(slot.level),apply=(mode,value=rule.value)=>{const bounded=Math.max(1,Math.min(100,Math.round(Number(value)||1)));slot.level=mode==="ultimecia"?252:mode==="maximum"?100+bounded:bounded;slot.levelRule=encounterLevelRule(slot.level);shell.refresh()};
    const mode=el("select",{"aria-label":"Enemy level rule",onchange:event=>{apply(event.target.value);renderEncounters()}},el("option",{value:"fixed"},"Fixed level"),el("option",{value:"maximum"},"Maximum level"),el("option",{value:"ultimecia"},"Ultimecia Castle: random 1–100"));
    if(rule.mode==="special")mode.append(el("option",{value:"special"},`Special (${slot.level})`));
    mode.value=rule.mode;
    return el("div",{class:"encounter-level-control"},mode,...(["fixed","maximum"].includes(rule.mode)?[numberControl(rule.value,1,100,1,value=>apply(rule.mode,value),{"aria-label":"Enemy level rule value"})]:[]));
  }
  function encounterDetail(row,prefs){const header=detailSection({className:"encounter-header-section",title:"FORMATION",body:[detailField({label:"STAGE ID",help:infoHelp("Selects the a0stg battle-stage model used behind this formation."),control:encounterSource(numberControl(row.stageId,0,255,1,value=>row.stageId=value),row,value=>value?.stageId,value=>row.stageId=Number(value)),pin:prefs?.pinButton("stageId","Stage")}),detailField({label:"FLAGS",help:infoHelp("The exact scene.out formation-flags byte. Its individual bits are not yet proven, so Lexeditor preserves and edits the stored byte without invented names."),control:encounterSource(numberControl(row.flags,0,255,1,value=>row.flags=value),row,value=>value?.flags,value=>row.flags=Number(value),value=>`0x${Number(value).toString(16).padStart(2,"0").toLocaleUpperCase()}`),pin:prefs?.pinButton("flags","Flags")}),detailField({label:"MAIN CAMERA",help:infoHelp("The first camera byte for this scene.out formation. The upstream parser calls it camera_main; its exact shot mapping is not yet documented."),control:encounterSource(numberControl(row.cameraMain,0,255,1,value=>row.cameraMain=value),row,value=>value?.cameraMain,value=>row.cameraMain=Number(value)),pin:prefs?.pinButton("cameraMain","Main camera")}),detailField({label:"SECONDARY CAMERA",help:infoHelp("The second camera byte for this scene.out formation. The upstream parser calls it camera_secondary; its exact shot mapping is not yet documented."),control:encounterSource(numberControl(row.cameraSecondary,0,255,1,value=>row.cameraSecondary=value),row,value=>value?.cameraSecondary,value=>row.cameraSecondary=Number(value)),pin:prefs?.pinButton("cameraSecondary","Secondary camera")})]});const slots=encounterSlotEditor(row);return sharedDetail({...row,name:`Encounter ${row.id}`},prefs,[header,detailSection({className:"encounter-slots-section",title:"ENEMY SLOTS",body:slots})],"encounter-detail")}
  const encounterSlotSelection=new Map();
  function encounterSlotEditor(row){
    const selected=encounterSlotSelection.get(row.id)??row.slots[0]?.slot;
    const slot=row.slots.find(entry=>entry.slot===selected)||row.slots[0];
    const list=el("div",{class:"encounter-slot-list","aria-label":"Enemy slots"});
    row.slots.forEach(entry=>list.append(el("button",{type:"button",class:entry===slot?"active":"","aria-pressed":String(entry===slot),onclick:()=>{encounterSlotSelection.set(row.id,entry.slot);renderEncounters()}},el("span",{},String(entry.slot+1)),el("span",{},enemyDisplayName(entry.enemyName)),el("span",{},entry.enabled?"Enabled":"Disabled"))));
    if(!slot)return list;
    const read=key=>value=>value?.slots?.find(entry=>entry.slot===slot.slot)?.[key];
    const field=(label,key,control,apply,help)=>detailField({label,control:encounterSource(control,row,read(key),apply),help:help?infoHelp(help):null});
    const bool=(label,key)=>field(label,key,el("input",{type:"checkbox",checked:slot[key],"aria-label":label,onchange:event=>{slot[key]=event.target.checked;shell.refresh();if(key==="enabled")renderEncounters()}}),value=>{slot[key]=Boolean(value);if(key==="enabled")renderEncounters()});
    const setEnemy=value=>{slot.enemyId=Number(value);slot.enemyName=enemyById(value).name;shell.refresh();renderEncounters()};
    const settings=el("div",{class:"encounter-slot-settings"},
      field("ENEMY","enemyId",enemySearchControl(slot.enemyId,`Choose enemy for slot ${slot.slot+1}`,setEnemy,()=>{state.selected.encounters=row.id;navigate("encounters")}),setEnemy),
      bool("VISIBLE","visible"),bool("LOADED","loaded"),bool("TARGETABLE","targetable"),
      ...["x","y","z"].map(axis=>field(axis.toUpperCase(),axis,numberControl(slot[axis],-32768,32767,1,value=>slot[axis]=value,{"aria-label":`Slot ${slot.slot+1} ${axis.toUpperCase()}`}),value=>slot[axis]=Number(value))),
      field("LEVEL RULE","level",encounterLevelControl(slot),value=>{slot.level=Number(value);renderEncounters()},"Use a fixed level, a maximum level, or random levels from 1 to 100 in Ultimecia Castle. Special values are kept until you choose a known rule."));
    if(!slot.enabled)settings.querySelectorAll("input,select,button").forEach(control=>control.disabled=true);
    return el("div",{class:"encounter-slot-editor"},list,el("div",{class:"encounter-slot-detail"},el("h3",{},`Slot ${slot.slot+1}`),bool("ENABLED","enabled"),settings));
  }
  function renderEncounters(){const rows=filtered("encounters",["name","id","stageId"]);showPaged("encounters",rows,[{key:"id",label:"ID"},{key:"name",label:"Encounter"},{key:"stageId",label:"Stage"},{key:"flags",label:"Flags",pinned:false,render:row=>`0x${Number(row.flags).toString(16).padStart(2,"0").toLocaleUpperCase()}`},{key:"cameraMain",label:"Main camera",pinned:false},{key:"cameraSecondary",label:"Secondary camera",pinned:false}],encounterDetail,"74px minmax(260px,1fr) 90px",{defaultSplit:32,minLeft:260,minRight:520});const title=window.LexeditorUI.sectionParts(document.querySelector(".encounter-slots-section")).title;if(title?.firstChild)title.firstChild.textContent="ENEMIES"}

  function worldRow(dataset,kind,id){return dataset?.world?.rows?.find(row=>row.kind===kind&&Number(row.id)===Number(id))}
  function worldNumber(row,key,min,max,label){const vanilla=worldRow(state.vanilla,row.kind,row.id),refs=state.references.map(reference=>({name:reference.name,shortName:reference.shortName,value:worldRow(state.referenceData[reference.id],row.kind,row.id)?.[key]})).filter(entry=>entry.value!==undefined);return sourceControl(numberControl(row[key],min,max,1,value=>row[key]=value,{"aria-label":label}),()=>row[key],vanilla?.[key],refs,value=>row[key]=Number(value))}
  function worldColorHex(value){return `#${(value||[0,0,0]).map(channel=>Math.max(0,Math.min(255,Number(channel)||0)).toString(16).padStart(2,"0")).join("")}`}
  function worldColor(row,key,label){const vanilla=worldRow(state.vanilla,row.kind,row.id),refs=state.references.map(reference=>({name:reference.name,shortName:reference.shortName,value:worldRow(state.referenceData[reference.id],row.kind,row.id)?.[key]})).filter(entry=>entry.value!==undefined),apply=value=>{const hex=Array.isArray(value)?worldColorHex(value):String(value);if(!/^#[0-9a-f]{6}$/i.test(hex))return;row[key]=[1,3,5].map(offset=>parseInt(hex.slice(offset,offset+2),16))},control=el("input",{type:"color",class:"world-color-input",value:worldColorHex(row[key]),"aria-label":label,onchange:event=>{apply(event.target.value);rerenderWorldMap();shell.refresh()}});return sourceControl(control,()=>row[key],vanilla?.[key],refs,apply,worldColorHex)}
  function worldSkySwatch(row){return el("span",{class:"world-sky-swatch","aria-label":`Sky gradient for record ${row.id}`,style:`background:linear-gradient(to bottom,${worldColorHex(row.skyTop)},${worldColorHex(row.skyCenter)},${worldColorHex(row.skyBottom)})`})}
  function railPointNumber(row,point,key){const find=dataset=>worldRow(dataset,"railTrack",row.id)?.points?.[point.id]?.[key],refs=state.references.map(reference=>({name:reference.name,shortName:reference.shortName,value:find(state.referenceData[reference.id])})).filter(entry=>entry.value!==undefined),update=value=>point[key]=Number(value);return sourceControl(numberControl(point[key],-2147483648,2147483647,1,update,{"aria-label":`Track ${row.id} point ${point.id} ${key.toLocaleUpperCase()}`}),()=>point[key],find(state.vanilla),refs,update)}
  function railTrackDetail(row,prefs){
    const vanilla=worldRow(state.vanilla,"railTrack",row.id),refs=key=>state.references.map(reference=>({name:reference.name,shortName:reference.shortName,value:worldRow(state.referenceData[reference.id],"railTrack",row.id)?.[key]})).filter(entry=>entry.value!==undefined),choices=row.points.map(point=>({value:point.id,name:`Point ${point.id}`})),stop=(key,label)=>{const control=selectControl(row[key],choices,value=>row[key]=value);control.setAttribute("aria-label",label);return sourceControl(control,()=>row[key],vanilla?.[key],refs(key),value=>row[key]=Number(value),value=>`Point ${value}`)},points=columnList({rows:row.points,key:point=>point.id,class:"rail-point-table ff8-record-list",editable:true,template:"70px repeat(3,minmax(110px,1fr))",columns:[{key:"id",label:"POINT",numberedId:true,sortable:false,render:point=>point.id},{key:"x",label:"X",help:"X world coordinate of this route point. Changing it moves the point.",numeric:true,sortable:false,render:point=>railPointNumber(row,point,"x")},{key:"y",label:"Y",help:"Y world coordinate of this route point. Changing it moves the point.",numeric:true,sortable:false,render:point=>railPointNumber(row,point,"y")},{key:"z",label:"Z",help:"Z world coordinate of this route point. Changing it moves the point.",numeric:true,sortable:false,render:point=>railPointNumber(row,point,"z")}]});
    return sharedDetail({...row,name:`TRAIN TRACK ${row.id}`},prefs,[detailSection({title:"TRAIN STOPS",body:[detailField({label:"STOP 1",help:infoHelp("Together with Stop 2, this keypoint defines one endpoint of the rail route used by this train track."),control:stop("trainStop1","Train stop 1")}),detailField({label:"STOP 2",help:infoHelp("Together with Stop 1, this keypoint defines the other endpoint of the rail route used by this train track."),control:stop("trainStop2","Train stop 2")})]}),detailSection({className:"rail-track-points",title:"KEYPOINTS",help:infoHelp("Ordered points that define this train route. X, Y, and Z are stored world coordinates. Move points to change the route; the number of points remains fixed."),body:[points]})],"world-map-detail world-rail");
  }
  const worldTexturePalettes={};
  function worldTextureDataset(){return state.activeSource==="mine"?"current":state.activeSource}
  function worldTextureDetail(row,prefs){
    const palette=Math.max(0,Math.min(row.paletteCount-1,Number(worldTexturePalettes[row.id]??0))),dataset=worldTextureDataset(),query=`dataset=${encodeURIComponent(dataset)}&palette=${palette}&v=${encodeURIComponent(row.sha256)}`,preview=el("img",{class:"world-texture-preview",src:`/assets/world-textures/${row.id}.png?${query}`,alt:`${row.name}, palette ${palette+1}`}),paletteSelect=selectControl(palette,Array.from({length:row.paletteCount},(_,id)=>({value:id,name:`Palette ${id+1}`})),value=>{worldTexturePalettes[row.id]=value;rerenderWorldMap()}),upload=el("input",{type:"file",accept:".tim,application/octet-stream",hidden:true}),replace=el("button",{type:"button",disabled:state.activeSource!=="mine",onclick:()=>upload.click()},"Replace TIM"),pending=el("div",{class:"world-texture-pending"},row.timBase64?"Replacement selected; Save applies it.":"No pending replacement."),exportLink=el("a",{href:`/assets/world-textures/${row.id}.tim?dataset=${encodeURIComponent(dataset)}`,download:`world-texture-${row.id+1}.tim`},"Export TIM");
    paletteSelect.setAttribute("aria-label",`${row.name} preview palette`);upload.onchange=async event=>{const file=event.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{row.timBase64=String(reader.result).split(",",2)[1]||"";pending.textContent=`${file.name} selected; Save validates and applies it.`;shell.refresh()};reader.onerror=()=>showAlert({title:"Could not read TIM",message:"The selected TIM file could not be read."});reader.readAsDataURL(file);event.target.value=""};
    const metadata=el("div",{class:"world-texture-metadata"},el("span",{},`${row.width} \u00d7 ${row.height}`),el("span",{},`${row.depth}-bit indexed`),el("span",{},`${row.paletteCount} palettes`),el("span",{},`${formatNumber(row.timBytes)} TIM bytes`)),controls=el("div",{class:"world-texture-controls"},detailField({label:"PREVIEW PALETTE",help:infoHelp("Choose the colours used to display this indexed image. This changes only the preview, not the saved texture."),control:paletteSelect}),metadata,el("div",{class:"world-texture-actions"},exportLink,replace,upload),pending);
    return sharedDetail(row,prefs,[detailSection({className:"world-texture-section",title:"WORLD TEXTURE",body:[el("div",{class:"world-texture-body"},preview,controls)]})],"world-map-detail world-texture");
  }
  // Packed block coordinates: FF8UltimateEditor/Cid/drawmapwidget.py.
  function worldDrawPosition(point){return {x:point.x&127,y:2*point.y+(point.x>>7)}}
  function worldDrawBytes(x,y){return {x:(x&127)|((y&1)<<7),y:y>>1}}
  const worldVisualView={scale:1,x:0,y:0};
  function worldMapNavigation(panel,stage){
    const view=worldVisualView,apply=()=>{stage.style.transform=`translate(${view.x}px,${view.y}px) scale(${view.scale})`};apply();
    panel.addEventListener('wheel',event=>{
      event.preventDefault();event.stopPropagation();
      const box=panel.getBoundingClientRect(),ratio=box.width/panel.offsetWidth;
      const x=(event.clientX-box.left)/ratio-panel.clientWidth/2,y=(event.clientY-box.top)/ratio-panel.clientHeight/2;
      const next=Math.max(1,Math.min(8,view.scale*Math.exp(-event.deltaY*.0015))),factor=next/view.scale;
      view.x=x-(x-view.x)*factor;view.y=y-(y-view.y)*factor;view.scale=next;
      if(next===1){view.x=0;view.y=0}apply();
    },{passive:false});
    let drag=null;
    panel.addEventListener('pointerdown',event=>{if(event.button!==1)return;event.preventDefault();panel.setPointerCapture(event.pointerId);drag={x:event.clientX,y:event.clientY}});
    panel.addEventListener('pointermove',event=>{if(!drag)return;const ratio=panel.getBoundingClientRect().width/panel.offsetWidth;view.x+=(event.clientX-drag.x)/ratio;view.y+=(event.clientY-drag.y)/ratio;drag={x:event.clientX,y:event.clientY};apply()});
    panel.addEventListener('pointerup',()=>{drag=null});panel.addEventListener('pointercancel',()=>{drag=null});
    panel.addEventListener('auxclick',event=>{if(event.button===1)event.preventDefault()});
    panel.addEventListener('dblclick',()=>{Object.assign(view,{scale:1,x:0,y:0});apply()});
  }
  function worldDrawPointDetail(row,prefs){
    const position=worldDrawPosition(row),marker=el("span",{class:"world-draw-marker",style:`left:${position.x/128*100}%;top:${position.y/96*100}%`}),map=el("button",{type:"button",class:"world-draw-map","aria-label":`Set Draw Point ${row.drawId} position`,onclick:event=>{const box=event.currentTarget.getBoundingClientRect();Object.assign(row,worldDrawBytes(Math.max(0,Math.min(127,Math.round((event.clientX-box.left)/box.width*128))),Math.max(0,Math.min(95,Math.round((event.clientY-box.top)/box.height*96)))));rerenderWorldMap();shell.refresh()}},marker,el("span",{class:"world-draw-map-axis y"},"96 BLOCK ROWS"),el("span",{class:"world-draw-map-axis x"},"128 BLOCK COLUMNS"));
    return sharedDetail({...row,name:`DRAW POINT ${row.drawId}`},prefs,[detailSection({className:"world-draw-position",title:"WORLD POSITION",help:infoHelp("Section 34 stores only this world Draw Point's X, Y, and sub-ID bytes. Its magic, quantity, and refill behavior live in FF8_EN.exe and are not invented here."),body:[map,el("p",{class:"world-draw-help"},"Click the grid to place the point, or enter exact byte coordinates."),detailField({label:"X",help:infoHelp("Packed position byte: its lower seven bits give the block column; its top bit gives the odd or even block row. Use the grid for visual placement."),control:worldNumber(row,"x",0,255,`Draw Point ${row.drawId} X`)}),detailField({label:"Y",help:infoHelp("Packed row byte. The block row is twice this value plus the top bit of X. Use the grid to stay within the map."),control:worldNumber(row,"y",0,255,`Draw Point ${row.drawId} Y`)}),detailField({label:"SUB-ID",help:infoHelp("The exact third byte in this world-position record. FF8 Ultimate Editor names it sub_id; its finer gameplay meaning is not proved, so Lexeditor does not assign a speculative label."),control:worldNumber(row,"subId",0,255,`Draw Point ${row.drawId} sub-ID`)})]})],"world-map-detail world-draw-point");
  }
  function worldFieldReturnDetail(row,prefs){return sharedDetail({...row,name:`FIELD RETURN ${row.id}`},prefs,[detailSection({title:"FIELD → WORLD POSITION",help:infoHelp("OpenVIII proves this as one entry in wmset section 9's field-to-world coordinate table. The entry index is a transition-location index, not a field ID. Lexeditor preserves the unresolved fourth word."),body:[detailField({label:"X",help:infoHelp("X coordinate for this record. Changing it moves the stored world position."),control:worldNumber(row,"x",-2147483648,2147483647,`Field return ${row.id} X`)}),detailField({label:"Y",help:infoHelp("Y coordinate for this record. Changing it moves the stored world position."),control:worldNumber(row,"y",-32768,32767,`Field return ${row.id} Y`)}),detailField({label:"Z",help:infoHelp("Z coordinate for this record. Changing it moves the stored world position."),control:worldNumber(row,"z",-2147483648,2147483647,`Field return ${row.id} Z`)}),detailField({label:"UNRESOLVED WORD",help:infoHelp("The final signed 16-bit word in this record has no proved gameplay name. It remains visible and byte-preserved, but cannot be edited as a guessed property."),control:readonlyField(row.unknown)})]})],"world-map-detail world-field-return")}
  function worldSkyDetail(row,prefs){return sharedDetail({...row,name:`SKY RECORD ${row.id}`},prefs,[detailSection({title:"WORLD POSITION",help:infoHelp("OpenVIII identifies these as the signed world coordinates for this sky and ambient colour record. The file stores them in X, Z, Y order; Lexeditor presents the world X, Y, Z order."),body:[detailField({label:"X",help:infoHelp("X coordinate for this record. Changing it moves the stored world position."),control:worldNumber(row,"x",-2147483648,2147483647,`Sky record ${row.id} X`)}),detailField({label:"Y",help:infoHelp("Y coordinate for this record. Changing it moves the stored world position."),control:worldNumber(row,"y",-2147483648,2147483647,`Sky record ${row.id} Y`)}),detailField({label:"Z",help:infoHelp("Z coordinate for this record. Changing it moves the stored world position."),control:worldNumber(row,"z",-2147483648,2147483647,`Sky record ${row.id} Z`)})]}),detailSection({className:"world-sky-colors",title:"SKY AND AMBIENT COLOURS",help:infoHelp("OpenVIII proves five RGB triples in each section 33 record. Lexeditor preserves each unused fourth colour byte and the unresolved record tail."),body:[detailField({label:"SHADOWS",help:infoHelp("Ambient shadow colour for this world colour record. Choose a colour and test the result at this location."),control:worldColor(row,"shadows",`Sky record ${row.id} shadows colour`)}),detailField({label:"VEHICLES",help:infoHelp("Vehicle colour value stored in this world colour record."),control:worldColor(row,"vehicles",`Sky record ${row.id} vehicles colour`)}),detailField({label:"SKY TOP",help:infoHelp("Colour at the top of the sky gradient."),control:worldColor(row,"skyTop",`Sky record ${row.id} sky top colour`)}),detailField({label:"SKY CENTRE",help:infoHelp("Colour in the middle of the sky gradient."),control:worldColor(row,"skyCenter",`Sky record ${row.id} sky centre colour`)}),detailField({label:"SKY BOTTOM",help:infoHelp("Colour at the bottom of the sky gradient."),control:worldColor(row,"skyBottom",`Sky record ${row.id} sky bottom colour`)})]})],"world-map-detail world-sky-detail")}
  function worldSegmentDetail(row){
    const region=worldRow(state.data,"region",row.id),blocks=el("div",{class:"world-segment-blocks"},...row.blocks.map(block=>el("div",{class:"world-segment-block"},`BLOCK ${block.id}`,el("small",{},`${block.polygonCount} polygons · ${block.vertexCount} vertices`))));
    return sharedDetail({...row,name:`WORLD SEGMENT ${row.id}`},null,[
      detailSection({title:"MAP POSITION",body:[detailField({label:"X",help:infoHelp("Read-only X cell coordinate in the world-map grid."),control:readonlyField(row.x)}),detailField({label:"Y",help:infoHelp("Read-only Y cell coordinate in the world-map grid."),control:readonlyField(row.y)}),detailField({label:"REGION ID",help:infoHelp("This region combines with the segment's ground type to choose which world-map encounter rule and encounter group apply here."),control:worldNumber(region,"regionId",0,255,`World segment ${row.id} region ID`)})]}),
      detailSection({title:"WMX GEOMETRY",help:infoHelp("Deling proves the group ID at the start of each 0x9000-byte WMX segment. Lexeditor changes only that value and preserves all polygon topology and unknown bytes."),body:[detailField({label:"GROUP ID",help:infoHelp("Stored geometry group for this segment. Its full effect in the game is not established. This is not the encounter group; use Encounter Rules to change battles."),control:worldNumber(row,"groupId",0,4294967295,`World segment ${row.id} group ID`)}),detailField({label:"POLYGONS",help:infoHelp("Number of terrain faces in this segment. This count is read-only."),control:readonlyField(row.polygonCount)}),detailField({label:"GROUND TYPES",help:infoHelp("Terrain codes used by the polygons in this segment. A ground code and the region ID select an encounter rule. These are stored codes, not counts."),control:el("span",{class:"world-ground-list"},row.groundTypes.join(", ")||"None")})]}),
      detailSection({title:"BLOCKS",help:infoHelp("Each world segment contains 16 smaller terrain blocks. Polygons are the faces that form the terrain; vertices are the points at their corners. These counts describe the stored geometry."),body:[blocks]})
    ],"world-map-detail world-segment-detail");
  }
  function renderWorldVisual(){
    const segments=state.data.world.rows.filter(row=>row.kind==="worldSegment").slice(0,32*24),selected=Math.max(0,Math.min(segments.length-1,Number(state.selected.world??0))),row=segments[selected];state.selected.world=selected;
    const dataset=worldTextureDataset(),image=el("img",{class:"world-visual-image",src:`/assets/world-map.png?dataset=${encodeURIComponent(dataset)}&v=${encodeURIComponent(state.data.world.sha256)}`,alt:"Rendered Final Fantasy VIII world map"});
    const cells=segments.map(segment=>{const region=worldRow(state.data,"region",segment.id);return el("button",{type:"button",class:`world-segment-cell${segment.id===selected?" selected":""}`,title:`Segment ${segment.id} · region ${region?.regionId??"?"} · group ${segment.groupId}`,"aria-label":`Select world segment ${segment.id}`,onclick:()=>{state.selected.world=segment.id;rerenderWorldMap()}})});
    const markers=state.data.world.drawPoints.filter(point=>point.x!==0||point.y!==0).map(point=>{
      const position=worldDrawPosition(point);if(position.y>=96)return null;
      return el("button",{type:"button",class:"world-map-marker",style:`left:${position.x/128*100}%;top:${position.y/96*100}%`,title:`Draw Point ${point.drawId} · click to edit`,"aria-label":`Open Draw Point ${point.drawId}`,onclick:event=>{event.stopPropagation();state.worldTab="drawPoints";state.selected.world=point.id;state.pages.world=0;state.filters.world="";state.modOnly=false;rerenderWorldMap()}});
    }).filter(Boolean);
    const stage=el("div",{class:"world-visual-stage"},image,...markers,el("div",{class:"world-segment-grid"},...cells));
    const panel=el("section",{class:"world-visual-panel","aria-label":"FF8 world map"},stage,el("div",{class:"world-map-help"},infoHelp("Red dots are world Draw Points. Click a dot to edit it. Use the mouse wheel to zoom, hold the middle mouse button to pan, and double-click to fit the map.")));
    worldMapNavigation(panel,stage);
    return el("div",{class:"world-visual-layout"},panel,worldSegmentDetail(row));
  }
  function worldDetail(row,prefs){
    if(row.kind==="region")return sharedDetail({...row,name:`REGION CELL ${row.id}`},prefs,[detailSection({title:"WORLD REGION",body:[detailField({label:"X",help:infoHelp("Read-only X cell coordinate in the world-map grid."),control:readonlyField(row.x)}),detailField({label:"Y",help:infoHelp("Read-only Y cell coordinate in the world-map grid."),control:readonlyField(row.y)}),detailField({label:"REGION ID",help:infoHelp("This region combines with ground type to choose which world-map encounter rule and encounter group apply in this segment."),control:worldNumber(row,"regionId",0,255,"World region ID")})]})],"world-map-detail");
    if(row.kind==="helper")return sharedDetail({...row,name:`ENCOUNTER RULE ${row.id}`},prefs,[detailSection({title:"REGION AND GROUND RULE",body:[detailField({label:"REGION ID",help:infoHelp("Region code matched by Encounter Rules together with the ground type to select battles."),control:worldNumber(row,"regionId",0,255,"Encounter rule region ID")}),detailField({label:"GROUND ID",help:infoHelp("Combined with Region ID, this terrain type selects the world-map encounter group used here."),control:worldNumber(row,"groundId",0,255,"Encounter rule ground ID")}),detailField({label:"ENCOUNTER GROUP",help:infoHelp("The section 4 group of eight scene.out encounter IDs used by this region and ground pair."),control:worldNumber(row,"encounterGroup",0,state.data.world.groups.length-1,"Encounter group")})]})],"world-map-detail");
    if(row.kind==="railTrack")return railTrackDetail(row,prefs);
    if(row.kind==="worldTexture")return worldTextureDetail(row,prefs);
    if(row.kind==="drawPoint")return worldDrawPointDetail(row,prefs);
    if(row.kind==="fieldReturn")return worldFieldReturnDetail(row,prefs);
    if(row.kind==="skyColor")return worldSkyDetail(row,prefs);
    const vanilla=worldRow(state.vanilla,"group",row.id),body=row.encounters.map((value,index)=>detailField({label:`SLOT ${index+1}`,help:infoHelp("Battle formation ID in this group. Find the same ID in Encounters to inspect or edit its enemies."),control:sourceControl(numberControl(value,0,1023,1,next=>row.encounters[index]=next,{"aria-label":`Encounter group ${row.id} slot ${index+1}`}),()=>row.encounters[index],vanilla?.encounters?.[index],[],next=>row.encounters[index]=Number(next))}));return sharedDetail({...row,name:`ENCOUNTER GROUP ${row.id}`},prefs,[detailSection({title:"SCENE.OUT ENCOUNTERS",body})],"world-map-detail world-group");
  }
  function renderWorldMapContent(mount=true){
    const tabsData=[{id:"map",label:"Map",help:"Click a map segment to inspect its region and terrain geometry. Red dots are draw points; click one to edit its position. Scroll to zoom, drag with the middle mouse button to pan, and double-click to fit."},{id:"regions",label:"Regions",help:"Assign a region code to each world-map cell. Encounter Rules match this code together with the ground type to choose a battle group. Changing a cell can change which battles occur there."},{id:"rules",label:"Encounter Rules",help:"Connect a region and ground type to an Encounter Group. Match the region and terrain shown on the Map page, then choose the group of battles for that combination."},{id:"groups",label:"Encounter Groups",help:"Choose the eight battle formation IDs in a world encounter group. Rules select these groups. Use the Encounters tab to inspect the enemies in each formation. Each slot is a stored entry, not a percentage."},{id:"fieldReturns",label:"Field → World",help:"Set world positions used when leaving a field location. The record index identifies a transition location, not a field map ID. Edit coordinates to move the arrival point; the unused word is preserved."},{id:"drawPoints",label:"Draw Points",help:"Move world draw points. Click the placement grid or edit the packed position bytes. This page does not change the magic, quantity, or refill behaviour."},{id:"skyColors",label:"Sky Colours",help:"Edit sky gradients and ambient colours at stored world positions. Select a record, change its position or colours, then test that area in the game."},{id:"rails",label:"Train Tracks",help:"Edit the points that form a train route and select its two stop points. Coordinates move the route; stop values select points already in that route."},{id:"textures",label:"World Textures",help:"Preview or replace world texture images. Choose a palette for the preview. Export TIM to edit the texture in a compatible tool, then Replace TIM and Save. Palette selection only changes the preview."}],wrap=content=>{const tabs=subtabBar({className:"world-map-tabs",tabs:tabsData,active:state.worldTab,label:"World map data",change:value=>{state.worldTab=value;state.pages.world=0;state.selected.world=null;rerenderWorldMap()}}),root=el("div",{class:"world-map-view"},tabs,content);if(mount)$("#main").replaceChildren(root);return root};
    if(state.worldTab==="map"){const toolbar=$("#toolbar");toolbar.replaceChildren();toolbar.hidden=true;return wrap(renderWorldVisual())}
    const kind={regions:"region",rules:"helper",groups:"group",fieldReturns:"fieldReturn",drawPoints:"drawPoint",skyColors:"skyColor",rails:"railTrack",textures:"worldTexture"}[state.worldTab],rows=state.data.world.rows.filter(row=>row.kind===kind),query=state.filters.world.trim().toLocaleLowerCase(),matching=rows.filter(row=>!query||JSON.stringify(row).toLocaleLowerCase().includes(query)),[sortKey,sortDirection]=state.sorts.world,visible=[...matching].sort((left,right)=>sortDirection*String(rowSortValue(left,sortKey)).localeCompare(String(rowSortValue(right,sortKey)),undefined,{numeric:true,sensitivity:"base"}));
    const columns=kind==="region"?[{key:"id",label:"CELL",help:"World grid cell number. Select it to edit its region code."},{key:"x",label:"X",help:"Stored X coordinate. Select the record for coordinate-specific help."},{key:"y",label:"Y",help:"Stored Y coordinate. Select the record for coordinate-specific help."},{key:"regionId",label:"REGION ID",help:"Region code used by encounter rules."}]:kind==="helper"?[{key:"id",label:"RULE",help:"Record number of a region and ground-type rule."},{key:"regionId",label:"REGION",help:"Region code matched by this rule."},{key:"groundId",label:"GROUND",help:"Terrain code matched by this rule."},{key:"encounterGroup",label:"GROUP",help:"Encounter group selected by this rule, or the group record number on the Groups page."}]:kind==="fieldReturn"?[{key:"id",label:"INDEX",help:"Transition-location index, not a field map ID."},{key:"x",label:"X",help:"Stored X coordinate. Select the record for coordinate-specific help."},{key:"y",label:"Y",help:"Stored Y coordinate. Select the record for coordinate-specific help."},{key:"z",label:"Z",help:"Stored Z coordinate. Select the record for coordinate-specific help."}]:kind==="drawPoint"?[{key:"drawId",label:"DRAW ID",help:"Identifier of this world draw point."},{key:"x",label:"X",help:"Stored X coordinate. Select the record for coordinate-specific help."},{key:"y",label:"Y",help:"Stored Y coordinate. Select the record for coordinate-specific help."},{key:"subId",label:"SUB-ID",help:"Stored sub-ID byte; its gameplay meaning is not yet established."}]:kind==="skyColor"?[{key:"id",label:"RECORD",help:"Identifier of this sky colour record."},{key:"skyTop",label:"SKY GRADIENT",help:"Preview of the top, centre, and bottom sky colours.",render:worldSkySwatch}]:kind==="railTrack"?[{key:"id",label:"TRACK",help:"Identifier of the train route."},{key:"pointCount",label:"POINTS",help:"Number of points forming the route."},{key:"trainStop1",label:"STOP 1",help:"First stop point in this route."},{key:"trainStop2",label:"STOP 2",help:"Second stop point in this route."}]:kind==="worldTexture"?[{key:"id",label:"TEXTURE",help:"Identifier of the world texture."},{key:"name",label:"ASSET",help:"Name of the texture image record."},{key:"paletteCount",label:"PALETTES",help:"Number of colour tables in this indexed image."},{key:"depth",label:"BPP",help:"Bits per pixel, which determines how pixel indices refer to palette colours."}]:[{key:"id",label:"GROUP",help:"Encounter group selected by this rule, or the group record number on the Groups page."},{key:"encounters",label:"ENCOUNTER IDS",help:"Eight battle formation IDs stored in this group. Inspect matching IDs in Encounters.",render:row=>row.encounters.join(", ")}];
    delete state.columnPrefs.world;
    const content=showPaged("world",visible,columns,worldDetail,kind==="group"?"90px minmax(280px,1fr)":kind==="skyColor"?"90px minmax(180px,1fr)":"90px repeat(3,minmax(80px,1fr))",{defaultSplit:43,minLeft:360,minRight:460},false);
    return wrap(content);
  }
  function renderWorldMap(){return renderWorldMapContent(true)}

  function refineRow(dataset,table,id){return dataset?.refine?.rows?.find(row=>row.table===table&&Number(row.id)===Number(id))}
  function refineReferences(row,field){return state.references.map(reference=>({name:reference.name,shortName:reference.shortName,value:refineRow(state.referenceData[reference.id],row.table,row.id)?.[field]})).filter(entry=>entry.value!==undefined)}
  function refineChoice(type,value){return state.data.refine.choices[type]?.find(entry=>Number(entry.id)===Number(value))?.name??`${type} ${value}`}
  function setRefineEntity(row,side,value){row[`${side}Id`]=Number(value);row[`${side}Name`]=refineChoice(row[`${side}Type`],value);row.name=`${row.inputName} → ${row.outputName}`;shell.refresh()}
  function refineEntityControl(row,side){
    const type=row[`${side}Type`],field=`${side}Id`,set=value=>setRefineEntity(row,side,value),origin=()=>{state.refineTab=row.table;state.selected.refine=row.id;navigate("refine")},prompt=`Select the ${type} used as this recipe's ${side}.`;
    if(type==="item")return itemSearchControl(row[field],prompt,set,origin);
    if(type==="magic")return magicSearchControl(row[field],prompt,set,origin);
    return selectControl(row[field],state.data.refine.choices[type]||[],set);
  }
  function refineSource(control,row,field,apply,format){const vanilla=refineRow(state.vanilla,row.table,row.id);return sourceControl(control,()=>row[field],vanilla?.[field],refineReferences(row,field),apply,format,{internal:true})}
  function refineDetail(row,prefs){
    const text=el("textarea",{rows:7,maxlength:600,"aria-label":`Displayed refine text for ${row.name}`,oninput:event=>{row.text=event.target.value;shell.refresh()}});text.value=row.text;
    const label=`${state.data.refine.tables.find(table=>table.id===row.table)?.name||row.table} ${row.id+1}`;
    const recipeFields=["input","output"].flatMap(side=>{
      const field=`${side}Id`,quantity=`${side}Quantity`,apply=value=>setRefineEntity(row,side,value);
      return [detailField({label:side==="input"?"INPUT":"OUTPUT",pin:prefs?.pinButton(`${side}Name`,side==="input"?"Input":"Output"),control:refineSource(refineEntityControl(row,side),row,field,apply,value=>refineChoice(row[`${side}Type`],value))}),detailField({label:side==="input"?"NEEDED":"RECEIVED",pin:prefs?.pinButton(quantity,side==="input"?"Needed":"Received"),dataType:"INT",min:0,max:255,control:refineSource(numberControl(row[quantity],0,255,1,value=>{row[quantity]=value;shell.refresh()},{"aria-label":`${side} quantity for refine recipe`}),row,quantity,value=>{row[quantity]=Number(value);shell.refresh()})})];
    });
    return sharedDetail({...row,id:row.id+1,name:label},prefs,[
      ...recipeFields,
      detailField({label:"RECIPE TEXT",pin:prefs?.pinButton("text","Recipe text"),help:infoHelp("Message shown in the game for this recipe. Update it when you change the ingredients or quantities; it does not set the conversion itself."),control:refineSource(text,row,"text",value=>row.text=String(value??""))}),
      detailField({label:"UNKNOWN",pin:prefs?.pinButton("unknown","Unknown"),help:infoHelp("This preserved 16-bit value has no proved gameplay meaning, so it is read-only."),control:readonlyField(row.unknown)})
    ],"refine-detail");
  }
