  function renderRefine(){
    const query=state.filters.refine.trim().toLocaleLowerCase(),rows=state.data.refine.rows.filter(row=>row.table===state.refineTab&&(!query||[row.id,row.groupName,row.inputName,row.outputName,row.text].some(value=>String(value??"").toLocaleLowerCase().includes(query)))),[sortKey,sortDirection]=state.sorts.refine,visible=[...rows].sort((left,right)=>sortDirection*String(rowSortValue(left,sortKey)).localeCompare(String(rowSortValue(right,sortKey)),undefined,{numeric:true,sensitivity:"base"}));
    const columns=[
      {key:"id",label:"ID",width:"58px",render:row=>row.id+1},
      {key:"groupName",label:"ABILITY",width:"minmax(120px,.65fr)",headerTitle:"Refine ability",render:row=>el("span",{title:row.groupDescription},row.groupName)},
      {key:"name",label:"RECIPE",width:"minmax(180px,1fr)",render:row=>el("span",{title:`${row.inputName} → ${row.outputName}`},`${row.inputName} → ${row.outputName}`)},
      ...[
        ["inputName","Input"],["inputQuantity","Needed"],
        ["outputName","Output"],["outputQuantity","Received"],
        ["text","Recipe text"]
      ].map(([key,label])=>({key,label,pinned:false,numeric:key.endsWith("Quantity")||key==="unknown",width:key.endsWith("Quantity")||key==="unknown"?"80px":"minmax(120px,1fr)"}))
    ];
    delete state.columnPrefs.refine;showPaged("refine",visible,columns,refineDetail,"36px minmax(50px,.65fr) minmax(60px,1fr)",{defaultSplit:55,minLeft:210,minRight:430,maxBarrels:5});
    const content=$("#main").firstElementChild,tabs=subtabBar({className:"refine-tabs",tabs:state.data.refine.tables.map(table=>({id:table.id,label:table.name})),active:state.refineTab,label:"Refine recipe tables",change:value=>{state.refineTab=value;state.pages.refine=0;state.selected.refine=null;renderRefine()}});$("#main").replaceChildren(LexeditorUI.stack(tabs,content));
  }

  function fieldMapRow(dataset,key){return dataset?.fields?.rows?.find(row=>row.key===key)}
  async function ensureFieldDetail(row){
    // A failed lazy read must remain a stable error state. Retrying it from the
    // render path created an endless request/render loop that made the detail
    // pane alternate between its full height and a clipped loading panel.
    if(row._loaded||row._loading||row._error)return;row._loading=true;
    try{
      const dataset=state.activeSource==="mine"?"current":state.activeSource;
      const current=await api(`/api/field?map=${encodeURIComponent(row.key)}&dataset=${encodeURIComponent(dataset)}`),vanilla=state.activeSource==="mine"?await api(`/api/field?map=${encodeURIComponent(row.key)}&dataset=vanilla`):current;
      Object.assign(row,current,{_loaded:true,_loading:false});
      const vanillaRow=fieldMapRow(state.vanilla,row.key);if(vanillaRow)Object.assign(vanillaRow,clone(vanilla),{_loaded:true,_loading:false});
      const baseIndex=state.base.fields?.findIndex(value=>value.key===row.key)??-1;if(baseIndex>=0)state.base.fields[baseIndex]=clone(row);
      await Promise.all(state.references.map(async reference=>{const referenceRow=fieldMapRow(state.referenceData[reference.id],row.key);if(!referenceRow)return;try{const value=await api(`/api/field?map=${encodeURIComponent(row.key)}&dataset=${encodeURIComponent(`reference:${reference.id}`)}`);Object.assign(referenceRow,clone(value),{_loaded:true,_loading:false})}catch(error){referenceRow._error=error.message||String(error)}}));
    }catch(error){row._loading=false;row._error=error.message||String(error)}
    if(state.tab==="maps"&&state.mapsTab==="field")renderMaps();else if(state.tab==="fields")renderFields();shell.refresh();
  }
  function fieldParamControl(row,entry){
    const param=entry.param,vanilla=fieldMapRow(state.vanilla,row.key)?.players?.[entry.player.id]?.params?.[param.id];
    if(!param.editable)return readonlyField(`Unsupported opcode 0x${Number(param.opcode).toString(16).toLocaleUpperCase()}`);
    return sourceControl(numberControl(param.value,0,0xFFFFFF,1,value=>param.value=value,{"aria-label":`${row.name} ${entry.player.entity} ${param.name}`}),()=>param.value,vanilla?.value,[],value=>param.value=Number(value));
  }
  function fieldEntranceControl(row,kind,entry,field,axis=null){
    const collection=kind==="gateway"?"gateways":"triggers",vanilla=fieldMapRow(state.vanilla,row.key)?.entrances?.[collection]?.[entry.id],read=value=>axis?value?.[field]?.[axis]:value?.[field],minimum=field==="fieldId"?0:field==="doorId"?0:-32768,maximum=field==="fieldId"?32767:field==="doorId"?255:32767,label=`${row.name} ${kind} ${entry.id+1} ${field}${axis?` ${axis}`:""}`;
    return sourceControl(numberControl(read(entry),minimum,maximum,1,value=>{if(axis)entry[field][axis]=value;else entry[field]=value},{"aria-label":label}),()=>read(entry),read(vanilla),[],value=>{if(axis)entry[field][axis]=Number(value);else entry[field]=Number(value)});
  }
  function fieldGatewayTargetControl(row,entry){const vanilla=fieldMapRow(state.vanilla,row.key)?.entrances?.gateways?.[entry.id]?.fieldId,choices=[{id:32767,name:"Unused"},...state.data.fields.rows.filter(value=>value.mapId!=null).map(value=>({id:value.mapId,name:`${value.mapId} · ${value.name}`}))],change=value=>entry.fieldId=Number(value);return sourceControl(selectControl(entry.fieldId,choices,change,{"aria-label":`${row.name} gateway ${entry.id+1} target field`}),()=>entry.fieldId,vanilla,[],change,value=>choices.find(choice=>Number(choice.id)===Number(value))?.name||value)}
  function fieldPointControl(row,kind,entry,point){return LexeditorUI.controlGroup(["x","y","z"].map(axis=>({label:axis.toLocaleUpperCase(),help:infoHelp(`${axis.toLocaleUpperCase()} field coordinate of this point. Moving an endpoint changes the crossing line; moving Destination changes the arrival position.`),control:fieldEntranceControl(row,kind,entry,point,axis)})))}
  function fieldDialogueReferences(row,lineId){return state.references.map(reference=>({name:reference.name,shortName:reference.shortName,value:fieldMapRow(state.referenceData[reference.id],row.key)?.dialogue?.[lineId]?.text})).filter(entry=>entry.value!==undefined)}
  function fieldDialogueSection(row){const vanilla=fieldMapRow(state.vanilla,row.key);if(!row.dialogue?.length)return LexeditorUI.notice({message:"This field map has no dialogue lines."});return detailSection({title:"DIALOGUE",help:infoHelp("Dialogue shown by this field's scripts. Edit a line to change its message; keep its number and control codes. Some unused fields contain Japanese test text that the current Western decoder displays incorrectly. This editor does not translate it."),body:LexeditorUI.stack({fill:false},...row.dialogue.map(line=>{const area=LexeditorUI.textArea({rows:3,"aria-label":`${row.name} dialogue line ${line.id}`,oninput:event=>{line.text=event.target.value;shell.refresh()}});area.value=line.text;const control=sourceControl(area,()=>line.text,vanilla?.dialogue?.[line.id]?.text,fieldDialogueReferences(row,line.id),value=>line.text=String(value));return detailField({label:`#${line.id}`,control})}))})}
  function fieldScriptReferences(row,methodId){return state.references.map(reference=>({name:reference.name,shortName:reference.shortName,value:fieldMapRow(state.referenceData[reference.id],row.key)?.scripts?.methods?.find(method=>method.id===methodId)?.source})).filter(entry=>entry.value!==undefined)}
  function fieldScriptsSection(row){const methods=row.scripts?.methods||[];if(!methods.length)return LexeditorUI.notice({message:"This field map has no JSM methods."});let methodId=Number(state.fieldScriptSelection[row.key]);if(!methods.some(method=>method.id===methodId))methodId=methods[0].id;state.fieldScriptSelection[row.key]=methodId;const method=methods.find(value=>value.id===methodId),vanilla=fieldMapRow(state.vanilla,row.key)?.scripts?.methods?.find(value=>value.id===methodId),picker=selectControl(methodId,methods.map(value=>({id:value.id,name:`${value.id} · ${value.name}`})),value=>{state.fieldScriptSelection[row.key]=Number(value);rerenderFields()},{"aria-label":`${row.name} field script`}),area=LexeditorUI.codeField({rows:18,wrap:"off",readOnly:!method.editable,"aria-label":`${row.name} script ${method.id}`,oninput:event=>{method.source=event.target.value;shell.refresh()}});area.value=method.source;const source=sourceControl(area,()=>method.source,vanilla?.source,fieldScriptReferences(row,method.id),value=>method.source=String(value),value=>`${String(value??"").split(/\r?\n/).filter(Boolean).length} lines`);return detailSection({title:"FIELD SCRIPTS",help:infoHelp(`Scripts control events and actions in this location. Select a script, then edit its instructions, one per line. Keep opcode names and operand order. Labels mark branch destinations. Save validates and rebuilds branches; unsupported methods remain read-only. There are ${row.scripts.opcodeCount} recognised opcode names.`),body:[LexeditorUI.controlGroup([{label:"Script",control:picker},LexeditorUI.detailNote(`${method.groupType.toLocaleUpperCase()} GROUP ${method.groupId} · ${method.instructionCount} WORDS`)]),!method.editable?LexeditorUI.detailNote("This method has an unknown opcode or a branch outside the method, so it remains read-only."):null,source]})}
  function fieldEncounterReferences(row,kind,slot=null){return state.references.map(reference=>{const encounters=fieldMapRow(state.referenceData[reference.id],row.key)?.randomEncounters,value=kind==="rate"?encounters?.rate:encounters?.formations?.[slot];return{name:reference.name,shortName:reference.shortName,value}}).filter(entry=>entry.value!==undefined)}
  function fieldEncounterSection(row){const encounters=row.randomEncounters;if(!encounters?.formations?.length)return LexeditorUI.notice({message:"This field map has no MRT/RAT random encounter pair."});const vanilla=fieldMapRow(state.vanilla,row.key)?.randomEncounters,choices=(state.data.encounters?.rows||[]).map(entry=>({id:entry.id,name:`${entry.id} · ${entry.name}`})),format=value=>choices.find(entry=>Number(entry.id)===Number(value))?.name||value,fields=encounters.formations.map((value,slot)=>{const apply=next=>encounters.formations[slot]=Number(next),control=selectControl(value,choices,apply);control.setAttribute("aria-label",`${row.name} random encounter formation ${slot+1}`);return detailField({label:`FORMATION ${slot+1}`,help:infoHelp("Battle formation selected by this field's MRT random encounter table."),control:sourceControl(control,()=>encounters.formations[slot],vanilla?.formations?.[slot],fieldEncounterReferences(row,"formation",slot),apply,format),dataType:"ENUM"})}),setRate=value=>encounters.rate=Number(value),rate=numberControl(encounters.rate,0,255,1,setRate,{"aria-label":`${row.name} random encounter rate`});fields.push(detailField({label:"ENCOUNTER RATE",help:infoHelp("Stored random encounter rate for this field. The exact conversion to time or distance between battles is not established here. Saving applies this value to all four rate entries."),control:sourceControl(rate,()=>encounters.rate,vanilla?.rate,fieldEncounterReferences(row,"rate"),setRate),dataType:"INT",min:0,max:255}));return detailSection({className:"field-encounter-section",title:"RANDOM ENCOUNTERS",help:infoHelp("Choose the four battle formations available for random encounters in this field. Inspect their enemies in the Encounters tab. Encounter Rate controls the stored rate for this field."),body:LexeditorUI.tileGrid(fields)})}
  function fieldBackgroundTile(dataset,row,tileId){return fieldMapRow(dataset,row.key)?.background?.tiles?.[tileId]}
  function fieldBackgroundReferences(row,tileId,field){return state.references.map(reference=>({name:reference.name,shortName:reference.shortName,value:fieldBackgroundTile(state.referenceData[reference.id],row,tileId)?.[field]})).filter(entry=>entry.value!==undefined)}
  function fieldBackgroundEdits(row){const base=state.base.fields?.find(value=>value.key===row.key)?.background,edits=[];if(!base)return edits;for(const tile of row.background?.tiles||[]){const before=base.tiles?.[tile.id];if(!before)continue;const edit={tile:tile.id};for(const field of row.background.editableFields||[])if(tile[field]!==before[field])edit[field]=tile[field];if(Object.keys(edit).length>1)edits.push(edit)}return edits}
  function fieldBackgroundPreviewState(row){let value=state.fieldBackgroundPreview[row.key];if(!value){value={layers:[...(row.background?.layers||[])],states:(row.background?.parameterStates||[]).filter(entry=>entry.state===0).map(entry=>`${entry.parameter}:${entry.state}`),hide:false};state.fieldBackgroundPreview[row.key]=value}return value}
  async function refreshFieldBackgroundPreview(row,image,status){const preview=fieldBackgroundPreviewState(row),token=Symbol("field-background-preview");image.lexRequest=token;status.textContent="Rendering field background…";try{const response=await fetch("/api/field/background-preview",post({map:row.key,dataset:state.activeSource==="mine"?"current":state.activeSource,edits:fieldBackgroundEdits(row),activeStates:preview.states.map(value=>{const [parameter,stateValue]=value.split(":").map(Number);return{parameter,state:stateValue}}),enabledLayers:preview.layers,hideBackground:preview.hide,highlightTile:state.fieldBackgroundSelection[row.key]??0}));if(!response.ok){const problem=await response.json().catch(()=>({}));throw new Error(problem.error||`HTTP ${response.status}`)}const blob=await response.blob();if(image.lexRequest!==token||!image.isConnected)return;const url=URL.createObjectURL(blob),old=image.lexObjectUrl;image.lexObjectUrl=url;image.onload=()=>{if(old)URL.revokeObjectURL(old)};image.src=url;status.textContent=`${row.background.variant} MAP · ${formatNumber(row.background.tileCount)} tiles · ${image.alt}` }catch(error){if(image.lexRequest===token){status.textContent=`Preview unavailable: ${error.message||error}`}}}
  function fieldBackgroundControl(row,tile,field,label,minimum,maximum,help){const vanilla=fieldBackgroundTile(state.vanilla,row,tile.id),references=fieldBackgroundReferences(row,tile.id,field),apply=value=>{tile[field]=field==="draw"?Boolean(value):Number(value);const image=document.querySelector(`.field-background-image[data-field-key="${CSS.escape(row.key)}"]`),status=image?.lexStatus;if(image&&status)refreshFieldBackgroundPreview(row,image,status);shell.refresh()};let control;if(field==="draw")control=el("input",{type:"checkbox",checked:tile.draw,"aria-label":`${row.name} tile ${tile.id} draw`,onchange:event=>apply(event.target.checked)});else control=numberControl(tile[field],minimum,maximum,1,apply,{"aria-label":`${row.name} tile ${tile.id} ${label}`});return detailField({label,help:infoHelp(help),control:sourceControl(control,()=>tile[field],vanilla?.[field],references,apply,field==="draw"?booleanMark:undefined),dataType:field==="draw"?"BOOL":"INT",min:field==="draw"?undefined:minimum,max:field==="draw"?undefined:maximum})}
  function fieldBackgroundSection(row){
    const background=row.background;
    if(!background?.tiles?.length)return LexeditorUI.detailNote(background?.error?`This background is read-only: ${background.error}`:"This field map has no MAP/MIM background.");
    const tileId=Math.max(0,Math.min(background.tileCount-1,Number(state.fieldBackgroundSelection[row.key])||0));
    state.fieldBackgroundSelection[row.key]=tileId;
    const preview=fieldBackgroundPreviewState(row),tile=background.tiles[tileId];
    const image=el("img",{class:"field-background-image","data-field-key":row.key,alt:`${row.name} composed background`});
    const status=LexeditorUI.detailNote("Rendering field background…");image.lexStatus=status;
    const redraw=()=>refreshFieldBackgroundPreview(row,image,status);
    const picker=numberControl(tileId,0,background.tileCount-1,1,value=>{state.fieldBackgroundSelection[row.key]=Number(value);rerenderFields()},{"aria-label":`${row.name} selected background tile`});
    const layers=LexeditorUI.toggleRow({label:"Preview layers",toggles:background.layers.map(layer=>({label:`Layer ${layer}`,checked:preview.layers.includes(layer),change:checked=>{preview.layers=checked?[...new Set([...preview.layers,layer])]:preview.layers.filter(value=>value!==layer);redraw()}}))});
    const states=background.parameterStates.length?LexeditorUI.toggleRow({label:"Preview parameter states",toggles:background.parameterStates.map(entry=>{
      const key=`${entry.parameter}:${entry.state}`;
      return {label:`P${entry.parameter} S${entry.state}`,checked:preview.states.includes(key),change:checked=>{preview.states=checked?[...new Set([...preview.states,key])]:preview.states.filter(value=>value!==key);redraw()}};
    })}):LexeditorUI.detailNote("No conditional states");
    const definitions=[
    ["x","DESTINATION X",-32768,32767,"Horizontal destination of this 16 by 16 tile."],["y","DESTINATION Y",-32768,32767,"Vertical destination of this 16 by 16 tile."],["z","DESTINATION Z",0,65535,"Draw-order depth stored by this tile."],["sourceX","SOURCE X",0,255,"Horizontal source coordinate in the MIM texture."],["sourceY","SOURCE Y",0,255,"Vertical source coordinate in the MIM texture."],["texture","TEXTURE",0,15,"MIM texture page selected by this tile."],["palette","PALETTE",0,15,"MIM palette selected by indexed-colour tiles."],["blend","ALPHA",0,3,"Two-bit alpha mode stored in the packed texture word."],["draw","DRAW",0,1,"When off, this tile draws black instead of its MIM pixels."],["depth","COLOUR TYPE",0,3,"Stored colour-depth selector used to read the MIM pixels."],["layer","LAYER",0,255,"New-format background layer used by the preview filter."],["blendType","ALPHA TYPE",0,4,"New-format pixel blend operation."],["parameter","PARAMETER",0,255,"Field-script background parameter. 255 is unconditional."],["state","STATE",0,255,"State paired with the background parameter."]
  ];
    const fields=definitions.filter(([field])=>background.editableFields.includes(field)).map(([field,label,min,max,help])=>fieldBackgroundControl(row,tile,field,label,min,max,help));
    const editor=LexeditorUI.stack({fill:false},
      detailField({label:"Tile",control:picker,help:infoHelp("Select an existing tile to edit. This does not add a tile.")}),
      detailField({label:"Layers",control:layers,help:infoHelp("Show or hide layers in the preview. These filters do not change the game.")}),
      detailField({label:"Parameter states",control:states,help:infoHelp("P is the parameter number and S is its required state. These filters change only the preview.")}),
      LexeditorUI.toggleRow({toggles:[{label:"Hide unconditional background",checked:preview.hide,help:"Hide tiles with parameter 255 to inspect conditional tiles. This changes only the preview.",change:checked=>{preview.hide=checked;redraw()}}]}),
      LexeditorUI.tileGrid(fields));
    requestAnimationFrame(redraw);
    return detailSection({title:"Background",help:infoHelp("The background is built from small image tiles. Select a tile, then change where it is drawn or which texture pixels it uses."),
      body:LexeditorUI.tileGrid([LexeditorUI.figureGrid([{media:image,caption:status}]),editor])});
  }
  function fieldWalkmeshVertex(dataset,row,triangleId,vertexId){return fieldMapRow(dataset,row.key)?.walkmesh?.triangles?.[triangleId]?.vertices?.[vertexId]}
  function fieldWalkmeshControl(row,triangle,vertex,field){const vanilla=fieldWalkmeshVertex(state.vanilla,row,triangle.id,vertex.id),references=state.references.map(reference=>({name:reference.name,shortName:reference.shortName,value:fieldWalkmeshVertex(state.referenceData[reference.id],row,triangle.id,vertex.id)?.[field]})).filter(entry=>entry.value!==undefined),minimum=field==="adjacent"?-1:-32768,maximum=field==="adjacent"?row.walkmesh.triangleCount-1:32767,apply=value=>vertex[field]=Number(value);return sourceControl(numberControl(vertex[field],minimum,maximum,1,apply,{"aria-label":`${row.name} triangle ${triangle.id} vertex ${vertex.id} ${field}`}),()=>vertex[field],vanilla?.[field],references,apply)}
  function fieldWalkmeshCanvas(row,selected,select){const canvas=el("canvas",{width:720,height:400,"aria-label":`${row.name} top-down X Z walkmesh preview`,onclick:event=>{const projection=canvas.lexProjection;if(!projection)return;const rect=canvas.getBoundingClientRect(),x=(event.clientX-rect.left)*canvas.width/rect.width,y=(event.clientY-rect.top)*canvas.height/rect.height;let nearest=selected.id,distance=Infinity;for(const triangle of row.walkmesh.triangles){const points=triangle.vertices.map(projection),cx=(points[0][0]+points[1][0]+points[2][0])/3,cy=(points[0][1]+points[1][1]+points[2][1])/3,next=(cx-x)**2+(cy-y)**2;if(next<distance){distance=next;nearest=triangle.id}}select(nearest)}}),draw=()=>{if(!canvas.isConnected)return;const triangles=row.walkmesh.triangles,values=triangles.flatMap(triangle=>triangle.vertices);let minX=Infinity,maxX=-Infinity,minZ=Infinity,maxZ=-Infinity;for(const vertex of values){minX=Math.min(minX,vertex.x);maxX=Math.max(maxX,vertex.x);minZ=Math.min(minZ,vertex.z);maxZ=Math.max(maxZ,vertex.z)}const padding=16,scale=Math.min((canvas.width-padding*2)/Math.max(1,maxX-minX),(canvas.height-padding*2)/Math.max(1,maxZ-minZ)),usedX=(maxX-minX)*scale,usedZ=(maxZ-minZ)*scale,offsetX=(canvas.width-usedX)/2,offsetY=(canvas.height-usedZ)/2,project=vertex=>[offsetX+(vertex.x-minX)*scale,canvas.height-offsetY-(vertex.z-minZ)*scale],ctx=canvas.getContext("2d");canvas.lexProjection=project;ctx.clearRect(0,0,canvas.width,canvas.height);ctx.lineWidth=1;ctx.strokeStyle="rgba(220,220,220,.38)";ctx.beginPath();for(const triangle of triangles){const points=triangle.vertices.map(project);ctx.moveTo(...points[0]);ctx.lineTo(...points[1]);ctx.lineTo(...points[2]);ctx.closePath()}ctx.stroke();const points=selected.vertices.map(project);ctx.beginPath();ctx.moveTo(...points[0]);ctx.lineTo(...points[1]);ctx.lineTo(...points[2]);ctx.closePath();ctx.fillStyle="rgba(214,34,52,.55)";ctx.fill();ctx.lineWidth=3;ctx.strokeStyle="#fff";ctx.stroke()};requestAnimationFrame(draw);return canvas}
  function fieldWalkmeshSection(row){
    const mesh=row.walkmesh;
    if(!mesh?.triangles?.length)return LexeditorUI.detailNote(mesh?.error?`This walkmesh is read-only: ${mesh.error}`:"This field map has no walkmesh.");
    const triangleId=Math.max(0,Math.min(mesh.triangleCount-1,Number(state.fieldWalkmeshSelection[row.key])||0));
    state.fieldWalkmeshSelection[row.key]=triangleId;
    const select=value=>{state.fieldWalkmeshSelection[row.key]=Math.max(0,Math.min(mesh.triangleCount-1,Number(value)||0));rerenderFields()};
    const triangle=mesh.triangles[triangleId],picker=numberControl(triangleId,0,mesh.triangleCount-1,1,select,{"aria-label":`${row.name} selected walkmesh triangle`});
    const vertices=triangle.vertices.map(vertex=>detailSection({title:`Vertex ${vertex.id+1}`,body:LexeditorUI.tileGrid(
      ["x","y","z","adjacent"].map(field=>detailField({label:field==="adjacent"?`Edge ${vertex.id+1}`:field.toLocaleUpperCase(),
        help:infoHelp(field==="adjacent"?"Neighbour triangle across this edge. Use -1 for no neighbour.":`${field.toLocaleUpperCase()} coordinate of this corner. Changing it reshapes the walkable triangle.`),
        control:fieldWalkmeshControl(row,triangle,vertex,field)})))}));
    return detailSection({title:"Walkmesh",help:infoHelp("The walkmesh is the surface on which characters can move. Click near a triangle or select its number. Move its corners with X, Y and Z. The preview shows X and Z only."),
      body:LexeditorUI.tileGrid([LexeditorUI.figureGrid([{media:fieldWalkmeshCanvas(row,triangle,select),caption:"Top-down X / Z · Click near a triangle to select it"}]),
        LexeditorUI.stack({fill:false},detailField({label:"Triangle",control:picker}),...vertices)])});
  }
  function fieldDetail(row,prefs){
    if(!row._loaded){ensureFieldDetail(row);return sharedDetail(row,prefs,[el("div",{class:"field-empty"},row._error?`This map could not be opened: ${row._error}`:"Reading this field map's JSM and SYM…")],"field-map-detail",row.key)}
    const entries=row.players.flatMap(player=>player.params.map(param=>({id:`${player.id}-${param.id}`,player,param}))),table=columnList({rows:entries,key:entry=>entry.id,class:"ff8-record-list field-card-table",editable:true,localSort:false,columns:[{key:"entity",label:"Entity",render:entry=>entry.player.entity},{key:"script",label:"Script",render:entry=>entry.player.script},{key:"parameter",label:"Parameter",help:"One of the seven values consumed by the CARDGAME field opcode.",render:entry=>entry.param.name},{key:"mode",label:"Source",help:"Literal stores a number in the script. Savemap reads the numbered runtime variable. Editing the value preserves this source type.",render:entry=>entry.param.mode==="literal"?"Literal":entry.param.mode==="variable"?"Savemap":"Unsupported"},{key:"value",label:"Value",help:"The exact 24-bit literal or savemap-variable number stored by this push instruction.",numeric:true,render:entry=>fieldParamControl(row,entry)}]});
    const gateways=columnList({rows:row.entrances.gateways,key:entry=>entry.id,class:"ff8-record-list field-gateway-table",editable:true,localSort:false,columns:[{key:"id",label:"GATE",render:entry=>entry.id+1},{key:"fieldId",label:"TARGET FIELD",help:"The field loaded after the player crosses this gateway line. Choose Unused to disable the slot.",render:entry=>fieldGatewayTargetControl(row,entry)},{key:"exitA",label:"EXIT LINE A",help:"First endpoint of the line the player crosses to leave this field.",render:entry=>fieldPointControl(row,"gateway",entry,"exitA")},{key:"exitB",label:"EXIT LINE B",help:"Second endpoint of the line the player crosses to leave this field.",render:entry=>fieldPointControl(row,"gateway",entry,"exitB")},{key:"destination",label:"DESTINATION",help:"Player position after the target field loads.",render:entry=>fieldPointControl(row,"gateway",entry,"destination")}]});
    const triggers=columnList({rows:row.entrances.triggers,key:entry=>entry.id,class:"ff8-record-list field-trigger-table",editable:true,localSort:false,columns:[{key:"id",label:"TRIGGER",render:entry=>entry.id+1},{key:"doorId",label:"DOOR ID",help:"The field-script door line selected when the player crosses this trigger. 255 disables the slot.",numeric:true,render:entry=>fieldEntranceControl(row,"trigger",entry,"doorId")},{key:"lineA",label:"TRIGGER LINE A",help:"First endpoint of the door or event trigger line.",render:entry=>fieldPointControl(row,"trigger",entry,"lineA")},{key:"lineB",label:"TRIGGER LINE B",help:"Second endpoint of the door or event trigger line.",render:entry=>fieldPointControl(row,"trigger",entry,"lineB")}]});
    const entranceSections=row.entrances.gateways.length?[detailSection({title:"GATEWAYS",help:infoHelp("An exit is a line between two points. Crossing it loads Target Field and places the player at Destination. Select Unused to disable an exit."),body:gateways}),detailSection({title:"TRIGGERS",help:infoHelp("A trigger is a line that starts a field-script door or event action when crossed. Set both endpoints and the Door ID. Door ID 255 disables the slot."),body:triggers})]:[LexeditorUI.notice({message:"This field map has no INF gateway or trigger records."})],body=[fieldEncounterSection(row),fieldBackgroundSection(row),fieldWalkmeshSection(row),fieldDialogueSection(row),fieldScriptsSection(row),...entranceSections,entries.length?detailSection({title:"TRIPLE TRIAD PLAYERS",help:infoHelp("Parameters passed by field scripts when starting a card game. Literal values are stored directly; Savemap values refer to runtime variables. Editing a variable number changes which variable is read."),body:table}):LexeditorUI.notice({message:"This map has no CARDGAME calls."}),detailSection({title:"NOT YET EDITABLE",help:infoHelp("These parts of the location are listed for reference. This editor cannot change them yet."),body:LexeditorUI.detailNote(row.unsupported.join(" / "))})];
    return sharedDetail({...row,id:row.mapId??row.id,name:row.name.toLocaleUpperCase()},prefs,body,"field-map-detail",`${row.key}${row.mapId==null?" - not in maplist":` - map ${row.mapId}`}`)
  }
  function buildFields(){const rows=filtered("fields",["name","key","group","mapId"]);return showPaged("fields",rows,[{key:"mapId",label:"MAP ID",help:"Number used to identify this field in MAPLIST. A dash means the archive is not listed; it may contain unused or test content.",numeric:true,numberedId:true,render:row=>row.mapId??"—"},{key:"name",label:"FIELD MAP",help:"Internal field archive name. Select a row to edit that location."},{key:"group",label:"GROUP",help:"Archive folder prefix used to organise fields. This is not an encounter group."},{key:"listed",label:"MAPLIST",help:"Whether this field appears in the game map list. A cross means it is not listed; it does not mean the archive is missing.",render:row=>row.listed?"✓":"×"}],fieldDetail,"90px minmax(180px,1fr) 90px 90px",{defaultSplit:34,minLeft:330,minRight:680},false)}
  function renderFields(){const root=buildFields();$("#main").replaceChildren(root);return root}
  function rerenderFields(){if(state.tab==="maps")renderMaps();else renderFields()}
  function rerenderWorldMap(){if(state.tab==="maps")renderMaps();else renderWorldMap()}
  function renderMaps(){
    // Build the selected view off-DOM and mount the complete Maps tree once.
    // The old two-step mount exposed an unwrapped split pane for one frame and
    // then detached it again, which caused the right and bottom panes to flash.
    const content=state.mapsTab==="world"?renderWorldMapContent(false):buildFields(),tabs=subtabBar({className:"ff8-maps-tabs",tabs:[{id:"field",label:"Field",help:"Edit individual locations: their battles, background tiles, walkable surfaces, dialogue, scripts, exits, and event triggers. Select a map in the list, then edit its details. A map absent from MAPLIST can be unused test content."},{id:"world",label:"World",help:"Edit the outdoor world. To change random battles, first find the region and terrain, then its Encounter Rule, then the linked Encounter Group. Other pages control travel positions, draw points, colours, tracks, and textures."}],active:state.mapsTab,label:"Maps",change:value=>{state.mapsTab=value;renderMaps()}});
    $("#main").replaceChildren(LexeditorUI.stack(tabs,content));
  }

  function initOwner(dataset,kind,id=0){const init=dataset?.init;if(!init)return null;if(kind==="general"||kind==="config")return init[kind];if(kind==="gf")return init.gfs.rows.find(row=>Number(row.id)===Number(id));if(kind==="character")return init.characters.rows.find(row=>Number(row.id)===Number(id));return null}
  function initFieldSource(field,kind,id=0){const vanilla=initOwner(state.vanilla,kind,id)?.fields?.find(value=>value.field===field.field),references=state.references.map(reference=>({name:reference.name,shortName:reference.shortName,value:initOwner(state.referenceData[reference.id],kind,id)?.fields?.find(value=>value.field===field.field)?.value})).filter(entry=>entry.value!==undefined);return sourceControl(fieldControl(field),()=>field.value,vanilla?.value,references,value=>field.value=field.control==="boolean"?Boolean(value):Number(value))}
  function startingFields(fields,kind,id=0){return LexeditorUI.tileGrid(fields.map(field=>detailField({label:field.label,help:field.help?infoHelp(field.help):null,control:initFieldSource(field,kind,id),dataType:field.control==="boolean"?"BOOL":field.lookup?.type==="enum"?"ENUM":field.lookup?.type==="flags"?"FLAGS":"INT",min:field.minimum,max:field.maximum})))}
  function startingPicker(label,value,rows,change){return detailField({label,control:selectControl(value,rows.map(row=>({id:row.id,name:row.name})),change)})}
  function initNestedReferences(read){return state.references.map(reference=>({name:reference.name,shortName:reference.shortName,value:read(state.referenceData[reference.id]?.init)})).filter(entry=>entry.value!==undefined)}
  function startingMagicControl(character,slot){const vanilla=state.vanilla.init.characters.rows.find(row=>row.id===character.id)?.magics[slot.slot],choices=state.data.init.choices.magic,setMagic=value=>{slot.magicId=Number(value);if(slot.magicId===0)slot.quantity=0;renderStartingData();shell.refresh()},magic=sourceControl(selectControl(slot.magicId,choices,setMagic),()=>slot.magicId,vanilla?.magicId,initNestedReferences(init=>init?.characters.rows.find(row=>row.id===character.id)?.magics[slot.slot]?.magicId),setMagic,value=>choices.find(entry=>Number(entry.id)===Number(value))?.name||value),quantity=sourceControl(numberControl(slot.quantity,0,100,1,value=>slot.quantity=value,{"aria-label":`Starting Magic quantity ${slot.slot+1}`}),()=>slot.quantity,vanilla?.quantity,initNestedReferences(init=>init?.characters.rows.find(row=>row.id===character.id)?.magics[slot.slot]?.quantity),value=>slot.quantity=Number(value));return{magic,quantity}}
  function startingInventoryControls(slot){const vanilla=state.vanilla.init.inventory.rows[slot.slot],choices=state.data.init.choices.items,setItem=value=>{slot.itemId=Number(value);if(slot.itemId===0)slot.quantity=0;renderStartingData();shell.refresh()},item=sourceControl(itemSelectControl(slot.itemId,choices,setItem),()=>slot.itemId,vanilla.itemId,initNestedReferences(init=>init?.inventory.rows[slot.slot]?.itemId),setItem,value=>choices.find(entry=>Number(entry.id)===Number(value))?.name||value),quantity=sourceControl(numberControl(slot.quantity,0,100,1,value=>slot.quantity=value,{"aria-label":`Starting item quantity ${slot.slot+1}`}),()=>slot.quantity,vanilla.quantity,initNestedReferences(init=>init?.inventory.rows[slot.slot]?.quantity),value=>slot.quantity=Number(value));return{item,quantity}}
  function renderStartingData(){
    const tabs=[{id:"general",label:"General",help:"Set the party, progress and options used when a new game begins."},{id:"characters",label:"Characters",help:"Set each character’s initial stats, equipment, status and magic stock."},{id:"inventory",label:"Inventory",help:"Set the items and quantities given at the start of a new game."}],toolbar=$("#toolbar");toolbar.hidden=false;toolbar.replaceChildren(subtabBar({tabs,active:state.startingTab,label:"Starting data",change:value=>{state.startingTab=value;renderStartingData()}}));
    let body,title;
    if(state.startingTab==="characters"){
      const rows=state.data.init.characters.rows,row=rows.find(value=>value.id===state.selected.startingCharacter)||rows[0];state.selected.startingCharacter=row.id;const pageSize=state.pageSizes.startingMagic,pages=Math.max(1,Math.ceil(row.magics.length/pageSize));state.pages.startingMagic=Math.min(state.pages.startingMagic,pages-1);const visible=row.magics.slice(state.pages.startingMagic*pageSize,(state.pages.startingMagic+1)*pageSize),controls=new Map(visible.map(slot=>[slot.slot,startingMagicControl(row,slot)])),table=columnList({rows:visible,key:slot=>slot.slot,class:"starting-magic-table ff8-record-list",editable:true,template:"70px minmax(180px,1fr) minmax(90px,130px)",columns:[{key:"slot",label:"Slot",render:slot=>slot.slot+1},{key:"magic",label:"Magic",render:slot=>controls.get(slot.slot).magic},{key:"quantity",label:"Quantity",numeric:true,render:slot=>controls.get(slot.slot).quantity}]}),pageBar=pager({page:state.pages.startingMagic,pages,total:row.magics.length,pageSize,noun:"magic slots",change:value=>{state.pages.startingMagic=value;renderStartingData()}});title="STARTING CHARACTERS";body=[startingPicker("CHARACTER",row.id,rows,value=>{state.selected.startingCharacter=value;state.pages.startingMagic=0;renderStartingData()}),detailSection({title:"CHARACTER STATE",body:startingFields(row.fields,"character",row.id)}),detailSection({title:"MAGIC STOCK",body:[table,pageBar]})];
    }else if(state.startingTab==="inventory"){
      const rows=state.data.init.inventory.rows,pageSize=state.pageSizes.startingInventory,pages=Math.max(1,Math.ceil(rows.length/pageSize));state.pages.startingInventory=Math.min(state.pages.startingInventory,pages-1);const visible=rows.slice(state.pages.startingInventory*pageSize,(state.pages.startingInventory+1)*pageSize),controls=new Map(visible.map(slot=>[slot.slot,startingInventoryControls(slot)])),table=columnList({rows:visible,key:slot=>slot.slot,class:"starting-inventory-table ff8-record-list lex-page-sized-table",editable:true,template:"70px minmax(220px,1fr) minmax(90px,140px)",columns:[{key:"slot",label:"Slot",render:slot=>slot.slot+1},{key:"item",label:"Item",render:slot=>controls.get(slot.slot).item},{key:"quantity",label:"Quantity",numeric:true,render:slot=>controls.get(slot.slot).quantity}]});table.style.setProperty("--lex-page-row-count",String(pageSize));const pageBar=pager({inline:true,page:state.pages.startingInventory,pages,total:rows.length,pageSize,noun:"inventory slots",change:value=>{state.pages.startingInventory=value;renderStartingData()}});title="STARTING INVENTORY";body=LexeditorUI.pagedPane(table,pageBar);
    }else{title="STARTING DATA";body=[detailSection({title:"PARTY AND PROGRESS",body:startingFields(state.data.init.general.fields,"general")}),detailSection({title:"CONFIG",body:startingFields(state.data.init.config.fields,"config")})]}
    $("#main").replaceChildren(detailPanel({heading:false,body}));
  }
