"""Synthetic native-rule integration fixtures; no proprietary game data."""
import hashlib
import struct

from ds1_effects_fixture import make_effects_archive, wrap
from plugins.ds1.formats import inflate, members, ItemDocument
from plugins.ds1 import stamina_patch as native


def make_native_archive():
    source = make_effects_archive()
    plain = bytearray(inflate(source))
    table = members(plain)["EquipParamWeapon.param"]
    # The existing fixture's first weapon becomes the real shield identity.
    struct.pack_into("<i", plain, table.offset + 48, 1453000)
    return wrap(plain, source)


def fake_executable(monkeypatch):
    data = bytearray((i * 17 + 3) % 256 for i in range(4096))
    offsets = {"BASELINE_OFFSET": 32, "LIGHT_OFFSET": 40, "MEDIUM_OFFSET": 44,
               "FACTOR_OFFSET": 256, "FRACTION_OFFSET": 512, "OVERLOAD_DISP_OFFSET": 64}
    for key, value in offsets.items():
        monkeypatch.setattr(native, key, value)
    struct.pack_into("<f", data, 32, 45)
    struct.pack_into("<f", data, 40, .25)
    struct.pack_into("<f", data, 44, .5)
    data = bytes(data)
    monkeypatch.setattr(native, "ORIGINAL_SIZE", len(data))
    monkeypatch.setattr(native, "ORIGINAL_SHA256", hashlib.sha256(data).hexdigest())
    return data


def fake_bands_executable(monkeypatch):
    """Same mapped layout, but generated bytes and fake overlay, never retail code."""
    from plugins.ds1 import load_bands_patch as patch
    data = bytearray(patch.BLOCK_OFFSET + 32)
    data[:2] = b"MZ"
    struct.pack_into("<I", data, 0x3C, 0x180)
    data[0x180:0x184] = b"PE\0\0"
    struct.pack_into("<HH", data, 0x184, 0x8664, 9)
    struct.pack_into("<H", data, 0x194, 240)
    optional = 0x198
    struct.pack_into("<H", data, optional, 0x20B)
    struct.pack_into("<I", data, optional + 4, patch.BLOCK_RVA)
    struct.pack_into("<I", data, optional + 56, patch.BLOCK_RVA)
    struct.pack_into("<II", data, optional + 144, patch.BLOCK_OFFSET, 32)
    last = optional + 240 + 8 * 40
    data[last:last + 8] = b".text\0\0\0"
    struct.pack_into("<4I", data, last + 8, 0x1182000, 0x2019000, 0x1182000, 0x1E70800)
    struct.pack_into("<I", data, last + 36, 0x60000020)
    data[-32:] = b"synthetic certificate overlay".ljust(32, b"!")
    struct.pack_into("<f", data, native.BASELINE_OFFSET, 45)
    struct.pack_into("<f", data, native.LIGHT_OFFSET, .25)
    struct.pack_into("<f", data, native.MEDIUM_OFFSET, .5)
    original = bytes(data)
    monkeypatch.setattr(native, "ORIGINAL_SIZE", len(original))
    monkeypatch.setattr(native, "MAX_NATIVE_SIZE", len(original) + patch.EXTENSION_SIZE)
    monkeypatch.setattr(native, "ORIGINAL_SHA256", hashlib.sha256(original).hexdigest())
    return original
