from pathlib import Path


def replace_once(path: Path, old: str, new: str, label: str) -> None:
    text = path.read_text(encoding="utf-8")
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"{label}: expected one match, found {count}")
    path.write_text(text.replace(old, new, 1), encoding="utf-8")


# Shared exact-byte revision + staged replacement primitive.
revision = Path("games/bannerlord/source_revision.py")
replace_once(
    revision,
    '''from hashlib import sha256\nfrom pathlib import Path\n''',
    '''from hashlib import sha256\nfrom pathlib import Path\nimport shutil\n\nfrom . import paths\n''',
    "revision imports",
)
replace_once(
    revision,
    '''def source_revision(path: Path) -> str:\n    path = Path(path)\n    if not path.is_file():\n        return ""\n    return sha256(path.read_bytes()).hexdigest()\n''',
    '''_UTF8_BOM = b"\\xef\\xbb\\xbf"\n\n\ndef revision_bytes(data: bytes) -> str:\n    return sha256(data).hexdigest()\n\n\ndef source_revision(path: Path) -> str:\n    path = Path(path)\n    if not path.is_file():\n        return ""\n    return revision_bytes(path.read_bytes())\n\n\ndef read_utf8_source(path: Path) -> tuple[str, str, str]:\n    """Read UTF-8 text without newline translation and retain BOM/revision state."""\n    raw = Path(path).read_bytes()\n    token = revision_bytes(raw)\n    if raw.startswith(_UTF8_BOM):\n        return raw.decode("utf-8-sig"), "utf-8-sig", token\n    return raw.decode("utf-8"), "utf-8", token\n\n\ndef encode_utf8_source(text: str, encoding: str) -> bytes:\n    if encoding not in {"utf-8", "utf-8-sig"}:\n        raise ValueError(f"Unsupported Bannerlord source encoding: {encoding}")\n    return str(text).encode(encoding)\n''',
    "revision byte helpers",
)
insert = '''\n\ndef replace_source_bytes(path: Path, data: bytes, expected) -> str:\n    """Stage exact bytes, recheck the loaded revision, back up, and replace atomically."""\n    path = Path(path)\n    token = str(expected or "").strip()\n    if not token:\n        raise ValueError("Structured save requires the loaded source revision; reload before saving")\n    if not path.is_file():\n        raise FileNotFoundError(path)\n    temporary = path.with_name(path.name + ".lexeditor.tmp")\n    backup = path.with_name(path.name + ".lexeditor.bak")\n    paths.clear_write_helper(temporary)\n    temporary.write_bytes(bytes(data))\n    try:\n        require_source_revision(path, token)\n        paths.clear_write_helper(backup)\n        shutil.copy2(path, backup)\n        # Backup creation can take non-trivial time on a slow disk. Recheck once\n        # more before the target replacement so a racing external edit wins.\n        require_source_revision(path, token)\n        temporary.replace(path)\n    except Exception:\n        temporary.unlink(missing_ok=True)\n        raise\n    return str(backup)\n'''
needle = '''MISSING_SOURCE_REVISION = "missing"\n'''
text = revision.read_text(encoding="utf-8")
if text.count(needle) != 1:
    raise SystemExit("revision writer insertion point changed")
text = text.replace(needle, insert + "\n" + needle, 1)
revision.write_text(text, encoding="utf-8")


# Gauntlet: whole-file revision, exact byte fidelity, safe reload.
gauntlet = Path("games/bannerlord/gauntlet_data.py")
replace_once(gauntlet, '''from pathlib import Path\nimport shutil\nimport xml.etree.ElementTree as ET\n\nfrom .paths import clear_write_helper, contained_project_path, is_contained_file\nfrom .xml_patch import scan_xml_start_tags, serialize_attribute\n''', '''from pathlib import Path\nimport xml.etree.ElementTree as ET\n\nfrom .paths import contained_project_path, is_contained_file\nfrom .source_revision import (\n    encode_utf8_source,\n    read_utf8_source,\n    replace_source_bytes,\n    require_source_revision,\n)\nfrom .xml_patch import scan_xml_start_tags, serialize_attribute\n''', "gauntlet imports")
replace_once(gauntlet, '''def read_prefab(project: Path, requested: str) -> dict:\n    path = _prefab_path(project, requested)\n    text = path.read_text(encoding="utf-8-sig")\n''', '''def read_prefab(project: Path, requested: str) -> dict:\n    path = _prefab_path(project, requested)\n    text, _encoding, revision = read_utf8_source(path)\n''', "gauntlet read")
replace_once(gauntlet, '''        "relativePath": path.relative_to(project.resolve()).as_posix(),\n        "elements": [_public(element) for element in elements],\n''', '''        "relativePath": path.relative_to(project.resolve()).as_posix(),\n        "sourceHash": revision,\n        "elements": [_public(element) for element in elements],\n''', "gauntlet hash")
replace_once(gauntlet, '''def save_prefab(project: Path, requested: str, edits: list[dict]) -> dict:\n    path = _prefab_path(project, requested)\n    text = path.read_text(encoding="utf-8-sig")\n''', '''def save_prefab(\n    project: Path,\n    requested: str,\n    edits: list[dict],\n    source_hash: str | None = None,\n) -> dict:\n    path = _prefab_path(project, requested)\n    text, encoding, loaded_revision = read_utf8_source(path)\n    if source_hash is not None:\n        require_source_revision(path, source_hash)\n''', "gauntlet save signature")
replace_once(gauntlet, '''    backup = path.with_name(path.name + ".lexeditor.bak")\n    if changed:\n        try:\n            ET.fromstring(candidate)\n        except ET.ParseError as error:\n            raise ValueError(f"Saving would create invalid Gauntlet XML: {error}") from error\n        clear_write_helper(backup)\n        shutil.copy2(path, backup)\n        temporary = path.with_name(path.name + ".lexeditor.tmp")\n        clear_write_helper(temporary)\n        temporary.write_text(candidate, encoding="utf-8")\n        temporary.replace(path)\n    result = read_prefab(project, requested)\n    result.update({"saved": changed, "backup": str(backup) if changed else ""})\n''', '''    backup = ""\n    if changed:\n        try:\n            ET.fromstring(candidate)\n        except ET.ParseError as error:\n            raise ValueError(f"Saving would create invalid Gauntlet XML: {error}") from error\n        backup = replace_source_bytes(\n            path, encode_utf8_source(candidate, encoding), source_hash or loaded_revision\n        )\n    result = read_prefab(project, requested)\n    result.update({"saved": changed, "backup": backup})\n''', "gauntlet staged write")


# ModuleData XML: same guarantees, including record lifecycle edits.
moduledata = Path("games/bannerlord/module_xml_data.py")
replace_once(moduledata, '''from .module_data import read_submodule\nfrom .xml_patch import scan_xml_start_tags, serialize_attribute, serialize_new_attribute\n''', '''from .module_data import read_submodule\nfrom .source_revision import (\n    encode_utf8_source,\n    read_utf8_source,\n    replace_source_bytes,\n    require_source_revision,\n)\nfrom .xml_patch import scan_xml_start_tags, serialize_attribute, serialize_new_attribute\n''', "moduledata imports")
replace_once(moduledata, '''def read_document(project: Path, requested: str, game_root: Path | None = None) -> dict:\n    path = _document_path(project, requested)\n    text = path.read_text(encoding="utf-8-sig")\n''', '''def read_document(project: Path, requested: str, game_root: Path | None = None) -> dict:\n    path = _document_path(project, requested)\n    text, _encoding, revision = read_utf8_source(path)\n''', "moduledata read")
replace_once(moduledata, '''        "relativePath": path.relative_to(project.resolve()).as_posix(),\n        "rootTag": root.tag,\n''', '''        "relativePath": path.relative_to(project.resolve()).as_posix(),\n        "sourceHash": revision,\n        "rootTag": root.tag,\n''', "moduledata hash")
replace_once(moduledata, '''def save_document(\n    project: Path,\n    requested: str,\n    edits: list[dict],\n    game_root: Path | None = None,\n    additions: list[dict] | None = None,\n) -> dict:\n    path = _document_path(project, requested)\n    text = path.read_text(encoding="utf-8-sig")\n''', '''def save_document(\n    project: Path,\n    requested: str,\n    edits: list[dict],\n    game_root: Path | None = None,\n    additions: list[dict] | None = None,\n    source_hash: str | None = None,\n) -> dict:\n    path = _document_path(project, requested)\n    text, encoding, loaded_revision = read_utf8_source(path)\n    if source_hash is not None:\n        require_source_revision(path, source_hash)\n''', "moduledata save signature")
replace_once(moduledata, '''    backup = path.with_name(path.name + ".lexeditor.bak")\n    if changed:\n        try:\n            ET.fromstring(candidate)\n        except ET.ParseError as error:\n            raise ValueError(f"Saving would create invalid ModuleData XML: {error}") from error\n        paths.clear_write_helper(backup)\n        shutil.copy2(path, backup)\n        temporary = path.with_name(path.name + ".lexeditor.tmp")\n        paths.clear_write_helper(temporary)\n        temporary.write_text(candidate, encoding="utf-8")\n        temporary.replace(path)\n    result = read_document(project, requested, game_root)\n    result.update({"saved": changed, "backup": str(backup) if changed else ""})\n''', '''    backup = ""\n    if changed:\n        try:\n            ET.fromstring(candidate)\n        except ET.ParseError as error:\n            raise ValueError(f"Saving would create invalid ModuleData XML: {error}") from error\n        backup = replace_source_bytes(\n            path, encode_utf8_source(candidate, encoding), source_hash or loaded_revision\n        )\n    result = read_document(project, requested, game_root)\n    result.update({"saved": changed, "backup": backup})\n''', "moduledata staged write")


# SubModule.xml: keep intentional ElementTree serialization, but close the revision race.
module = Path("games/bannerlord/module_data.py")
replace_once(module, '''from pathlib import Path\nimport re\nimport shutil\nimport xml.etree.ElementTree as ET\n\nfrom . import paths\n''', '''from io import BytesIO\nfrom pathlib import Path\nimport re\nimport xml.etree.ElementTree as ET\n\nfrom . import paths\nfrom .source_revision import replace_source_bytes, require_source_revision, source_revision\n''', "module imports")
replace_once(module, '''def save_module(path: Path, payload: dict) -> dict:\n    path = Path(path)\n    path = paths.contained_project_path(path.parent, path.name, require_file=True)\n''', '''def save_module(path: Path, payload: dict, source_hash: str | None = None) -> dict:\n    path = Path(path)\n    path = paths.contained_project_path(path.parent, path.name, require_file=True)\n    loaded_revision = source_revision(path)\n    if source_hash is not None:\n        require_source_revision(path, source_hash)\n''', "module save signature")
replace_once(module, '''    backup = path.with_name(path.name + ".lexeditor.bak")\n    if changes:\n        paths.clear_write_helper(backup)\n        shutil.copy2(path, backup)\n        ET.indent(tree, space="  ")\n        temporary = path.with_name(path.name + ".lexeditor.tmp")\n        paths.clear_write_helper(temporary)\n        tree.write(temporary, encoding="utf-8", xml_declaration=True, short_empty_elements=True)\n        temporary.replace(path)\n    return {"saved": changes, "backup": str(backup) if changes else "", "module": read_submodule(path)}\n''', '''    backup = ""\n    if changes:\n        ET.indent(tree, space="  ")\n        output = BytesIO()\n        tree.write(output, encoding="utf-8", xml_declaration=True, short_empty_elements=True)\n        backup = replace_source_bytes(path, output.getvalue(), source_hash or loaded_revision)\n    return {"saved": changes, "backup": backup, "module": read_submodule(path)}\n''', "module staged write")


# MSBuild/raw source: preserve existing encoding/newlines and use the staged writer.
project = Path("games/bannerlord/project_data.py")
replace_once(project, '''from .module_data import read_submodule\nfrom .paths import clear_write_helper, contained_game_path, contained_project_path\n''', '''from .module_data import read_submodule\nfrom .paths import contained_game_path, contained_project_path\nfrom .source_revision import replace_source_bytes, require_source_revision, revision_bytes\n''', "project imports")
replace_once(project, '''def save_project_properties(path: Path, edits: dict) -> dict:\n''', '''def save_project_properties(path: Path, edits: dict, source_hash: str | None = None) -> dict:\n''', "project save signature")
replace_once(project, '''    raw = path.read_text(encoding="utf-8-sig")\n    candidate = raw\n    saved = 0\n''', '''    raw_bytes = path.read_bytes()\n    raw, encoding = _decode_source(raw_bytes)\n    loaded_revision = revision_bytes(raw_bytes)\n    if source_hash is not None:\n        require_source_revision(path, source_hash)\n    newline = "\\r\\n" if "\\r\\n" in raw else "\\n" if "\\n" in raw else "\\r" if "\\r" in raw else "\\n"\n    candidate = raw\n    saved = 0\n''', "project read fidelity")
replace_once(project, '''        insertion = f"{indentation}  <{name}>{escaped}</{name}>\\n"\n''', '''        insertion = f"{indentation}  <{name}>{escaped}</{name}>{newline}"\n''', "project insertion newline")
replace_once(project, '''    backup = path.with_name(path.name + ".lexeditor.bak")\n    if saved:\n        ET.fromstring(candidate)\n        clear_write_helper(backup)\n        shutil.copy2(path, backup)\n        temporary = path.with_name(path.name + ".lexeditor.tmp")\n        clear_write_helper(temporary)\n        temporary.write_text(candidate, encoding="utf-8")\n        temporary.replace(path)\n    return {\n        "saved": saved,\n        "backup": str(backup) if saved else "",\n''', '''    backup = ""\n    if saved:\n        ET.fromstring(candidate)\n        try:\n            encoded = candidate.encode(encoding)\n        except UnicodeEncodeError as error:\n            raise ValueError(f"Project text cannot be encoded as {encoding}") from error\n        backup = replace_source_bytes(path, encoded, source_hash or loaded_revision)\n    return {\n        "saved": saved,\n        "backup": backup,\n''', "project staged write")
replace_once(project, '''    current_text, encoding = _decode_source(target.read_bytes())\n    if original_text is None:\n''', '''    raw_bytes = target.read_bytes()\n    current_text, encoding = _decode_source(raw_bytes)\n    loaded_revision = revision_bytes(raw_bytes)\n    if original_text is None:\n''', "raw source loaded revision")
replace_once(project, '''    backup = target.with_name(target.name + ".lexeditor.bak")\n    clear_write_helper(backup)\n    shutil.copy2(target, backup)\n    temporary = target.with_name(target.name + ".lexeditor.tmp")\n    clear_write_helper(temporary)\n    # Write encoded bytes so Python's platform newline translation cannot\n    # rewrite raw-source line endings on Windows. The selected codec still\n    # preserves an existing UTF-8 BOM when one was present on load.\n    temporary.write_bytes(candidate.encode(encoding))\n    temporary.replace(target)\n    result = read_source(project, requested)\n    result.update({"saved": 1, "backup": str(backup)})\n''', '''    try:\n        encoded = candidate.encode(encoding)\n    except UnicodeEncodeError as error:\n        raise ValueError(f"Source text cannot be encoded as {encoding}") from error\n    backup = replace_source_bytes(target, encoded, loaded_revision)\n    result = read_source(project, requested)\n    result.update({"saved": 1, "backup": backup})\n''', "raw source staged write")


# Custom skill/effect C# writers.
skill = Path("games/bannerlord/skill_data.py")
replace_once(skill, '''from .paths import clear_write_helper, contained_project_path\n''', '''from .paths import contained_project_path\nfrom .source_revision import (\n    encode_utf8_source,\n    read_utf8_source,\n    replace_source_bytes,\n    require_source_revision,\n)\n''', "skill imports")
replace_once(skill, '''    text = path.read_text(encoding="utf-8-sig")\n    attributes = _definition_records(\n''', '''    text, _encoding, _revision = read_utf8_source(path)\n    attributes = _definition_records(\n''', "skill read")
replace_once(skill, '''def save_skill_definitions(project: Path, payload: dict) -> dict:\n    path = _source_path(project, "CustomSkillDefinitions.cs", require_file=True)\n''', '''def save_skill_definitions(project: Path, payload: dict, source_hash: str | None = None) -> dict:\n    path = _source_path(project, "CustomSkillDefinitions.cs", require_file=True)\n''', "skill save signature")
replace_once(skill, '''    text = path.read_text(encoding="utf-8-sig")\n    attributes = _definition_records(\n''', '''    text, encoding, loaded_revision = read_utf8_source(path)\n    if source_hash is not None:\n        require_source_revision(path, source_hash)\n    attributes = _definition_records(\n''', "skill save read")
replace_once(skill, '''    backup = path.with_name(path.name + ".lexeditor.bak")\n    if changed:\n        clear_write_helper(backup)\n        shutil.copy2(path, backup)\n        temporary = path.with_name(path.name + ".lexeditor.tmp")\n        clear_write_helper(temporary)\n        temporary.write_text(candidate, encoding="utf-8")\n        temporary.replace(path)\n    result = read_skill_definitions(project)\n    result.update({"saved": changed, "backup": str(backup) if changed else ""})\n''', '''    backup = ""\n    if changed:\n        backup = replace_source_bytes(\n            path, encode_utf8_source(candidate, encoding), source_hash or loaded_revision\n        )\n    result = read_skill_definitions(project)\n    result.update({"saved": changed, "backup": backup})\n''', "skill staged write")
replace_once(skill, '''    text = path.read_text(encoding="utf-8-sig")\n    rows = _effect_records(text)\n''', '''    text, _encoding, _revision = read_utf8_source(path)\n    rows = _effect_records(text)\n''', "effect read")
replace_once(skill, '''def save_effect_definitions(project: Path, edits: list[dict]) -> dict:\n    path = _source_path(project, "CustomSkillEffectRanges.cs", require_file=True)\n    text = path.read_text(encoding="utf-8-sig")\n''', '''def save_effect_definitions(\n    project: Path, edits: list[dict], source_hash: str | None = None\n) -> dict:\n    path = _source_path(project, "CustomSkillEffectRanges.cs", require_file=True)\n    text, encoding, loaded_revision = read_utf8_source(path)\n    if source_hash is not None:\n        require_source_revision(path, source_hash)\n''', "effect save signature")
replace_once(skill, '''    backup = path.with_name(path.name + ".lexeditor.bak")\n    if changed_records:\n        clear_write_helper(backup)\n        shutil.copy2(path, backup)\n        temporary = path.with_name(path.name + ".lexeditor.tmp")\n        clear_write_helper(temporary)\n        temporary.write_text(candidate, encoding="utf-8")\n        temporary.replace(path)\n    result = read_effect_definitions(project)\n''', '''    backup = ""\n    if changed_records:\n        backup = replace_source_bytes(\n            path, encode_utf8_source(candidate, encoding), source_hash or loaded_revision\n        )\n    result = read_effect_definitions(project)\n''', "effect staged write")
replace_once(skill, '''            "backup": str(backup) if changed_records else "",\n''', '''            "backup": backup,\n''', "effect backup result")


# Perk/XP C# writers.
perk = Path("games/bannerlord/perk_data.py")
replace_once(perk, '''from .paths import clear_write_helper, contained_project_path\n''', '''from .paths import contained_project_path\nfrom .source_revision import (\n    encode_utf8_source,\n    read_utf8_source,\n    replace_source_bytes,\n    require_source_revision,\n)\n''', "perk imports")
replace_once(perk, '''    text = path.read_text(encoding="utf-8-sig")\n    rows = _perk_records(text)\n''', '''    text, _encoding, _revision = read_utf8_source(path)\n    rows = _perk_records(text)\n''', "perk read")
replace_once(perk, '''def save_perk_definitions(project: Path, edits: list[dict]) -> dict:\n    """Edit only balance-safe perk fields; lookup identity remains stable."""\n    path = _source_path(project, "CustomSkillPerks.cs", require_file=True)\n    text = path.read_text(encoding="utf-8-sig")\n''', '''def save_perk_definitions(\n    project: Path, edits: list[dict], source_hash: str | None = None\n) -> dict:\n    """Edit only balance-safe perk fields; lookup identity remains stable."""\n    path = _source_path(project, "CustomSkillPerks.cs", require_file=True)\n    text, encoding, loaded_revision = read_utf8_source(path)\n    if source_hash is not None:\n        require_source_revision(path, source_hash)\n''', "perk save signature")
replace_once(perk, '''    backup = path.with_name(path.name + ".lexeditor.bak")\n    if changed_records:\n        clear_write_helper(backup)\n        shutil.copy2(path, backup)\n        temporary = path.with_name(path.name + ".lexeditor.tmp")\n        clear_write_helper(temporary)\n        temporary.write_text(candidate, encoding="utf-8")\n        temporary.replace(path)\n    result = read_perk_definitions(project)\n    result.update({"saved": len(changed_records), "backup": str(backup) if changed_records else ""})\n''', '''    backup = ""\n    if changed_records:\n        backup = replace_source_bytes(\n            path, encode_utf8_source(candidate, encoding), source_hash or loaded_revision\n        )\n    result = read_perk_definitions(project)\n    result.update({"saved": len(changed_records), "backup": backup})\n''', "perk staged write")
replace_once(perk, '''    text = path.read_text(encoding="utf-8-sig")\n    rows = _xp_source_records(text)\n''', '''    text, _encoding, _revision = read_utf8_source(path)\n    rows = _xp_source_records(text)\n''', "xp read")
replace_once(perk, '''def save_xp_source_definitions(project: Path, edits: list[dict]) -> dict:\n    """Edit fallback XP awards while keeping source lookup keys stable."""\n    path = _source_path(project, "CustomSkillXpSourcesConfig.cs", require_file=True)\n    text = path.read_text(encoding="utf-8-sig")\n''', '''def save_xp_source_definitions(\n    project: Path, edits: list[dict], source_hash: str | None = None\n) -> dict:\n    """Edit fallback XP awards while keeping source lookup keys stable."""\n    path = _source_path(project, "CustomSkillXpSourcesConfig.cs", require_file=True)\n    text, encoding, loaded_revision = read_utf8_source(path)\n    if source_hash is not None:\n        require_source_revision(path, source_hash)\n''', "xp save signature")
replace_once(perk, '''    backup = path.with_name(path.name + ".lexeditor.bak")\n    if changed_records:\n        clear_write_helper(backup)\n        shutil.copy2(path, backup)\n        temporary = path.with_name(path.name + ".lexeditor.tmp")\n        clear_write_helper(temporary)\n        temporary.write_text(candidate, encoding="utf-8")\n        temporary.replace(path)\n    result = read_xp_source_definitions(project)\n    result.update({"saved": len(changed_records), "backup": str(backup) if changed_records else ""})\n''', '''    backup = ""\n    if changed_records:\n        backup = replace_source_bytes(\n            path, encode_utf8_source(candidate, encoding), source_hash or loaded_revision\n        )\n    result = read_xp_source_definitions(project)\n    result.update({"saved": len(changed_records), "backup": backup})\n''', "xp staged write")


# MCM default C# writer.
settings = Path("games/bannerlord/settings_data.py")
replace_once(settings, '''from .paths import clear_write_helper, contained_project_path\n''', '''from .paths import contained_project_path\nfrom .source_revision import (\n    encode_utf8_source,\n    read_utf8_source,\n    replace_source_bytes,\n    require_source_revision,\n)\n''', "settings imports")
replace_once(settings, '''    text = path.read_text(encoding="utf-8-sig")\n    rows = _parse_settings(text)\n''', '''    text, _encoding, _revision = read_utf8_source(path)\n    rows = _parse_settings(text)\n''', "settings read")
replace_once(settings, '''def save_mcm_defaults(project: Path, edits: list[dict]) -> dict:\n    path = _settings_path(project, require_file=True)\n    text = path.read_text(encoding="utf-8-sig")\n''', '''def save_mcm_defaults(\n    project: Path, edits: list[dict], source_hash: str | None = None\n) -> dict:\n    path = _settings_path(project, require_file=True)\n    text, encoding, loaded_revision = read_utf8_source(path)\n    if source_hash is not None:\n        require_source_revision(path, source_hash)\n''', "settings save signature")
replace_once(settings, '''    backup = path.with_name(path.name + ".lexeditor.bak")\n    if changed:\n        clear_write_helper(backup)\n        shutil.copy2(path, backup)\n        temporary = path.with_name(path.name + ".lexeditor.tmp")\n        clear_write_helper(temporary)\n        temporary.write_text(candidate, encoding="utf-8")\n        temporary.replace(path)\n    result = read_mcm_defaults(project)\n    result.update({"saved": len(changed), "backup": str(backup) if changed else ""})\n''', '''    backup = ""\n    if changed:\n        backup = replace_source_bytes(\n            path, encode_utf8_source(candidate, encoding), source_hash or loaded_revision\n        )\n    result = read_mcm_defaults(project)\n    result.update({"saved": len(changed), "backup": backup})\n''', "settings staged write")


# Server passes the loaded revision all the way into every structured writer.
server = Path("games/bannerlord/server.py")
replace_once(server, '''                payload = self.read_json()\n                require_source_revision(source, payload.pop("sourceHash", None))\n                result = save_module(source, payload)\n''', '''                payload = self.read_json()\n                source_hash = payload.pop("sourceHash", None)\n                require_source_revision(source, source_hash)\n                result = save_module(source, payload, source_hash=source_hash)\n''', "server module revision")
replace_once(server, '''                require_source_revision(source, payload.pop("sourceHash", None))\n                self.send_json(attach_source_revision(save_skill_definitions(PROJECT, payload)))\n''', '''                source_hash = payload.pop("sourceHash", None)\n                require_source_revision(source, source_hash)\n                self.send_json(attach_source_revision(save_skill_definitions(PROJECT, payload, source_hash=source_hash)))\n''', "server skill revision")
replace_once(server, '''                require_source_revision(source, payload.pop("sourceHash", None))\n                self.send_json(attach_source_revision(save_effect_definitions(PROJECT, list(payload.get("edits") or []))))\n''', '''                source_hash = payload.pop("sourceHash", None)\n                require_source_revision(source, source_hash)\n                self.send_json(attach_source_revision(save_effect_definitions(PROJECT, list(payload.get("edits") or []), source_hash=source_hash)))\n''', "server effect revision")
replace_once(server, '''                require_source_revision(source, payload.pop("sourceHash", None))\n                self.send_json(attach_source_revision(save_perk_definitions(PROJECT, list(payload.get("edits") or []))))\n''', '''                source_hash = payload.pop("sourceHash", None)\n                require_source_revision(source, source_hash)\n                self.send_json(attach_source_revision(save_perk_definitions(PROJECT, list(payload.get("edits") or []), source_hash=source_hash)))\n''', "server perk revision")
replace_once(server, '''                require_source_revision(source, payload.pop("sourceHash", None))\n                self.send_json(attach_source_revision(save_xp_source_definitions(PROJECT, list(payload.get("edits") or []))))\n''', '''                source_hash = payload.pop("sourceHash", None)\n                require_source_revision(source, source_hash)\n                self.send_json(attach_source_revision(save_xp_source_definitions(PROJECT, list(payload.get("edits") or []), source_hash=source_hash)))\n''', "server xp revision")
replace_once(server, '''                require_source_revision(source, payload.pop("sourceHash", None))\n                self.send_json(attach_source_revision(save_mcm_defaults(PROJECT, list(payload.get("edits") or []))))\n''', '''                source_hash = payload.pop("sourceHash", None)\n                require_source_revision(source, source_hash)\n                self.send_json(attach_source_revision(save_mcm_defaults(PROJECT, list(payload.get("edits") or []), source_hash=source_hash)))\n''', "server settings revision")
replace_once(server, '''        if path == "/api/module-data/save":\n            try:\n                payload = self.read_json()\n                self.send_json(\n                    save_document(\n                        PROJECT,\n                        str(payload.get("path") or ""),\n                        list(payload.get("edits") or []),\n                    )\n                )\n''', '''        if path == "/api/module-data/save":\n            try:\n                payload = self.read_json()\n                requested = str(payload.get("path") or "")\n                snapshot = read_document(PROJECT, requested)\n                source = Path(str(snapshot.get("path") or ""))\n                source_hash = payload.get("sourceHash")\n                require_source_revision(source, source_hash)\n                self.send_json(\n                    save_document(\n                        PROJECT, requested, list(payload.get("edits") or []),\n                        source_hash=source_hash,\n                    )\n                )\n''', "server moduledata revision")
replace_once(server, '''        if path == "/api/gauntlet/save":\n            try:\n                payload = self.read_json()\n                self.send_json(\n                    save_prefab(\n                        PROJECT,\n                        str(payload.get("path") or ""),\n                        list(payload.get("edits") or []),\n                    )\n                )\n''', '''        if path == "/api/gauntlet/save":\n            try:\n                payload = self.read_json()\n                requested = str(payload.get("path") or "")\n                snapshot = read_prefab(PROJECT, requested)\n                source = Path(str(snapshot.get("path") or ""))\n                source_hash = payload.get("sourceHash")\n                require_source_revision(source, source_hash)\n                self.send_json(\n                    save_prefab(\n                        PROJECT, requested, list(payload.get("edits") or []),\n                        source_hash=source_hash,\n                    )\n                )\n''', "server gauntlet revision")
replace_once(server, '''                require_source_revision(project_file, payload.pop("sourceHash", None))\n                result = save_project_properties(project_file, dict(payload.get("edits") or {}))\n''', '''                source_hash = payload.pop("sourceHash", None)\n                require_source_revision(project_file, source_hash)\n                result = save_project_properties(\n                    project_file, dict(payload.get("edits") or {}), source_hash=source_hash\n                )\n''', "server project revision")


# Dynamic XML editor revision tokens + explicit reload actions.
gauntlet_editor = Path("games/bannerlord/editor_gauntlet.js")
replace_once(gauntlet_editor, '''async function loadGauntlet(path,ask=true){\n''', '''async function reloadGauntlet(){\n  if(!state.gauntlet)return;\n  await loadGauntlet(state.gauntlet.relativePath,true);\n}\n\nasync function loadGauntlet(path,ask=true){\n''', "gauntlet reload")
replace_once(gauntlet_editor, '''  const master=el("div",{class:"bl-master"},\n    el("div",{class:"bl-master-head"},el("strong",{},`Widgets (${state.gauntlet.elementCount||0})`)),\n''', '''  const master=el("div",{class:"bl-master"},\n    el("div",{class:"bl-master-head"},el("strong",{},`Widgets (${state.gauntlet.elementCount||0})`),\n      el("button",{type:"button",onclick:()=>reloadGauntlet()},"Reload")),\n''', "gauntlet reload button")
replace_once(gauntlet_editor, '''  const result=await post("/api/gauntlet/save",{path:state.gauntlet.relativePath,edits});\n''', '''  const result=await post("/api/gauntlet/save",{\n    path:state.gauntlet.relativePath,edits,sourceHash:state.savedGauntlet.sourceHash||""\n  });\n''', "gauntlet revision payload")
moduledata_editor = Path("games/bannerlord/editor_moduledata.js")
replace_once(moduledata_editor, '''async function loadModuleData(path,ask=true){\n''', '''async function reloadModuleData(){\n  if(!state.moduleData)return;\n  await loadModuleData(state.moduleData.relativePath,true);\n}\n\nasync function loadModuleData(path,ask=true){\n''', "moduledata reload")
replace_once(moduledata_editor, '''    const result=prepareModuleData(await post("/api/module-data/save",{path:state.moduleData.relativePath,edits:[payload]}));\n''', '''    const result=prepareModuleData(await post("/api/module-data/save",{\n      path:state.moduleData.relativePath,edits:[payload],sourceHash:state.savedModuleData.sourceHash||""\n    }));\n''', "moduledata lifecycle revision")
replace_once(moduledata_editor, '''  const master=el("div",{class:"bl-master"},\n    el("div",{class:"bl-master-head"},el("strong",{},`${state.moduleData.rootTag} (${state.moduleData.recordCount||0})`)),\n''', '''  const master=el("div",{class:"bl-master"},\n    el("div",{class:"bl-master-head"},el("strong",{},`${state.moduleData.rootTag} (${state.moduleData.recordCount||0})`),\n      el("button",{type:"button",onclick:()=>reloadModuleData()},"Reload")),\n''', "moduledata reload button")
replace_once(moduledata_editor, '''async function saveModuleData(){const edits=moduleDataEdits();if(!edits.length)return;const result=prepareModuleData(await post("/api/module-data/save",{path:state.moduleData.relativePath,edits}));state.moduleData=result;state.savedModuleData=clone(result);if(!(result.records||[]).some(record=>record.path===state.moduleDataRecordPath))applyModuleDataRecordSelection(result.records?.[0])}\n''', '''async function saveModuleData(){const edits=moduleDataEdits();if(!edits.length)return;const result=prepareModuleData(await post("/api/module-data/save",{path:state.moduleData.relativePath,edits,sourceHash:state.savedModuleData.sourceHash||""}));state.moduleData=result;state.savedModuleData=clone(result);if(!(result.records||[]).some(record=>record.path===state.moduleDataRecordPath))applyModuleDataRecordSelection(result.records?.[0])}\n''', "moduledata revision payload")


# Regression tests: exact-byte stale protection and fidelity across every text-preserving writer.
source_tests = Path("tests/test_bannerlord_source_revision.py")
text = source_tests.read_text(encoding="utf-8")
text = text.replace('''import tempfile\nimport unittest\n\nfrom games.bannerlord.source_revision import attach_source_revision, require_source_revision, source_revision\n''', '''import shutil\nimport tempfile\nimport unittest\nfrom unittest.mock import patch\n\nfrom games.bannerlord.source_revision import (\n    attach_source_revision, replace_source_bytes, require_source_revision, source_revision\n)\n''', 1)
marker = '''    def test_missing_revision_is_rejected(self):\n'''
addition = '''    def test_staged_writer_rechecks_after_backup_before_replacing_target(self):\n        with tempfile.TemporaryDirectory() as name:\n            source=Path(name)/"source.cs";source.write_bytes(b"before\\r\\n")\n            token=source_revision(source);real_copy2=shutil.copy2\n            def race(src,dst,*args,**kwargs):\n                result=real_copy2(src,dst,*args,**kwargs)\n                source.write_bytes(b"external\\r\\n")\n                return result\n            with patch("games.bannerlord.source_revision.shutil.copy2",side_effect=race):\n                with self.assertRaisesRegex(ValueError,"changed on disk"):\n                    replace_source_bytes(source,b"ours\\r\\n",token)\n            self.assertEqual(source.read_bytes(),b"external\\r\\n")\n            self.assertFalse(source.with_name(source.name+".lexeditor.tmp").exists())\n\n'''
if text.count(marker) != 1: raise SystemExit("source revision test insertion point changed")
source_tests.write_text(text.replace(marker, addition + marker, 1), encoding="utf-8")


gauntlet_tests = Path("tests/test_bannerlord_gauntlet.py")
text = gauntlet_tests.read_text(encoding="utf-8")
marker = '''    def test_prefab_root_redirection_outside_project_is_rejected(self):\n'''
addition = '''    def test_unrelated_external_prefab_change_rejects_stale_save(self):\n        temporary, project, source = self.fixture()\n        try:\n            value=read_prefab(project,"GUI/Prefabs/Mission/LexerMoraleBars.xml")\n            widget=next(row for row in value["elements"] if row["tag"]=="Widget")\n            source.write_text(PREFAB.replace("preserve this comment","externally changed comment"),encoding="utf-8")\n            before=source.read_bytes()\n            with self.assertRaisesRegex(ValueError,"changed on disk"):\n                save_prefab(project,value["relativePath"],[{"elementPath":widget["path"],"tag":widget["tag"],"attribute":"SuggestedHeight","originalValue":"24","value":30}],source_hash=value["sourceHash"])\n            self.assertEqual(source.read_bytes(),before);self.assertFalse(source.with_name(source.name+".lexeditor.bak").exists())\n        finally: temporary.cleanup()\n\n    def test_prefab_save_preserves_utf8_bom_and_crlf(self):\n        temporary, project, source = self.fixture()\n        try:\n            source.write_bytes(b"\\xef\\xbb\\xbf"+PREFAB.replace("\\n","\\r\\n").encode("utf-8"))\n            value=read_prefab(project,"GUI/Prefabs/Mission/LexerMoraleBars.xml")\n            widget=next(row for row in value["elements"] if row["tag"]=="Widget")\n            save_prefab(project,value["relativePath"],[{"elementPath":widget["path"],"tag":widget["tag"],"attribute":"SuggestedHeight","originalValue":"24","value":30}],source_hash=value["sourceHash"])\n            raw=source.read_bytes();self.assertTrue(raw.startswith(b"\\xef\\xbb\\xbf"));body=raw[3:]\n            self.assertIn(b'SuggestedHeight="30"',body);self.assertNotIn(b"\\n",body.replace(b"\\r\\n",b""))\n        finally: temporary.cleanup()\n\n    def test_gauntlet_editor_sends_revision_and_exposes_reload(self):\n        text=(Path(__file__).resolve().parents[1]/"games"/"bannerlord"/"editor_gauntlet.js").read_text(encoding="utf-8")\n        self.assertIn('sourceHash:state.savedGauntlet.sourceHash||""',text);self.assertIn("async function reloadGauntlet",text);self.assertIn('onclick:()=>reloadGauntlet()',text)\n\n'''
if text.count(marker) != 1: raise SystemExit("gauntlet test insertion point changed")
gauntlet_tests.write_text(text.replace(marker, addition + marker, 1), encoding="utf-8")


moduledata_tests = Path("tests/test_bannerlord_moduledata.py")
text = moduledata_tests.read_text(encoding="utf-8")
marker = '''    def test_moduledata_root_redirection_outside_project_is_rejected(self):\n'''
addition = '''    def test_unrelated_external_moduledata_change_rejects_stale_save(self):\n        temporary, project, source = self.fixture()\n        try:\n            value=read_document(project,"ModuleData/items.xml");item=next(row for row in value["elements"] if row["tag"]=="Item")\n            source.write_text(ITEMS.replace("preserve module-specific data","externally changed comment"),encoding="utf-8");before=source.read_bytes()\n            with self.assertRaisesRegex(ValueError,"changed on disk"):\n                save_document(project,value["relativePath"],[{"elementPath":item["path"],"tag":"Item","attribute":"weight","originalValue":"0.2","value":0.4}],source_hash=value["sourceHash"])\n            self.assertEqual(source.read_bytes(),before);self.assertFalse(source.with_name(source.name+".lexeditor.bak").exists())\n        finally: temporary.cleanup()\n\n    def test_moduledata_save_preserves_utf8_bom_and_crlf(self):\n        temporary, project, source = self.fixture()\n        try:\n            source.write_bytes(b"\\xef\\xbb\\xbf"+ITEMS.replace("\\n","\\r\\n").encode("utf-8"))\n            value=read_document(project,"ModuleData/items.xml");item=next(row for row in value["elements"] if row["tag"]=="Item")\n            save_document(project,value["relativePath"],[{"elementPath":item["path"],"tag":"Item","attribute":"weight","originalValue":"0.2","value":0.4}],source_hash=value["sourceHash"])\n            raw=source.read_bytes();self.assertTrue(raw.startswith(b"\\xef\\xbb\\xbf"));body=raw[3:]\n            self.assertIn(b'weight="0.4"',body);self.assertNotIn(b"\\n",body.replace(b"\\r\\n",b""))\n        finally: temporary.cleanup()\n\n    def test_moduledata_editor_sends_revision_and_exposes_reload(self):\n        text=(Path(__file__).resolve().parents[1]/"games"/"bannerlord"/"editor_moduledata.js").read_text(encoding="utf-8")\n        self.assertIn('sourceHash:state.savedModuleData.sourceHash||""',text);self.assertIn("async function reloadModuleData",text);self.assertIn('onclick:()=>reloadModuleData()',text)\n\n'''
if text.count(marker) != 1: raise SystemExit("moduledata test insertion point changed")
moduledata_tests.write_text(text.replace(marker, addition + marker, 1), encoding="utf-8")


plugin_tests = Path("tests/test_bannerlord_plugin.py")
text = plugin_tests.read_text(encoding="utf-8")
marker = '''    def test_custom_skill_and_effect_source_editors(self):\n'''
addition = '''    def test_text_preserving_project_skill_and_effect_writers_keep_bom_crlf(self):\n        from games.bannerlord.project_data import read_project_file, save_project_properties\n        from games.bannerlord.skill_data import read_effect_definitions, read_skill_definitions, save_effect_definitions, save_skill_definitions\n        with tempfile.TemporaryDirectory() as name:\n            project=Path(name);(project/"src").mkdir()\n            csproj=project/"LexerSkillTweaks.csproj";csproj_text=CSPROJ.replace("><",">\\r\\n<")+"\\r\\n";csproj.write_bytes(b"\\xef\\xbb\\xbf"+csproj_text.encode())\n            model=read_project_file(csproj);save_project_properties(csproj,{"OutputPath":"out\\\\"})\n            raw=csproj.read_bytes();self.assertTrue(raw.startswith(b"\\xef\\xbb\\xbf"));self.assertNotIn(b"\\n",raw[3:].replace(b"\\r\\n",b""));self.assertIn(b"<OutputPath>out\\\\</OutputPath>",raw)\n            skills_path=project/"src/CustomSkillDefinitions.cs";skills_path.write_bytes(b"\\xef\\xbb\\xbf"+(SKILL_DEFINITIONS+"\\r\\n").encode())\n            skills=read_skill_definitions(project);save_skill_definitions(project,{"attributes":[{"index":0,"originalId":"Sanguis","fields":{"name":"Blood"}}],"skills":[]})\n            raw=skills_path.read_bytes();self.assertTrue(raw.startswith(b"\\xef\\xbb\\xbf"));self.assertTrue(raw.endswith(b"\\r\\n"))\n            effects_path=project/"src/CustomSkillEffectRanges.cs";effects_path.write_bytes(b"\\xef\\xbb\\xbf"+(EFFECT_DEFINITIONS+"\\r\\n").encode())\n            effects=read_effect_definitions(project);save_effect_definitions(project,[{"index":0,"originalId":effects["effects"][0]["id"],"fields":{"defaultLow":140}}])\n            raw=effects_path.read_bytes();self.assertTrue(raw.startswith(b"\\xef\\xbb\\xbf"));self.assertTrue(raw.endswith(b"\\r\\n"))\n\n'''
if text.count(marker) != 1: raise SystemExit("plugin fidelity test insertion point changed")
plugin_tests.write_text(text.replace(marker, addition + marker, 1), encoding="utf-8")


perk_tests = Path("tests/test_bannerlord_perks_runtime.py")
text = perk_tests.read_text(encoding="utf-8")
marker = '''    def test_deployment_status_uses_launcher_version_semantics_and_blocks_missing_dependency(self):\n'''
addition = '''    def test_perk_and_xp_writers_preserve_bom_and_crlf(self):\n        from games.bannerlord.perk_data import read_perk_definitions,read_xp_source_definitions,save_perk_definitions,save_xp_source_definitions\n        with tempfile.TemporaryDirectory() as name:\n            project=Path(name);(project/"src").mkdir();perk_path=project/"src/CustomSkillPerks.cs";xp_path=project/"src/CustomSkillXpSourcesConfig.cs"\n            perk_path.write_bytes(b"\\xef\\xbb\\xbf"+PERKS.replace("\\n","\\r\\n").encode());xp_path.write_bytes(b"\\xef\\xbb\\xbf"+XP.replace("\\n","\\r\\n").encode())\n            perks=read_perk_definitions(project)["perks"];save_perk_definitions(project,[{"index":1,"originalId":perks[1]["id"],"fields":{"level":55}}])\n            sources=read_xp_source_definitions(project)["sources"];save_xp_source_definitions(project,[{"index":1,"originalId":sources[1]["id"],"fields":{"defaultAmount":0.5}}])\n            for path in (perk_path,xp_path):\n                raw=path.read_bytes();self.assertTrue(raw.startswith(b"\\xef\\xbb\\xbf"));self.assertNotIn(b"\\n",raw[3:].replace(b"\\r\\n",b""))\n\n'''
if text.count(marker) != 1: raise SystemExit("perk fidelity test insertion point changed")
perk_tests.write_text(text.replace(marker, addition + marker, 1), encoding="utf-8")


settings_tests = Path("tests/test_bannerlord_settings.py")
text = settings_tests.read_text(encoding="utf-8")
marker = '''    def test_settings_write_helpers_do_not_follow_existing_hardlinks(self):\n'''
addition = '''    def test_settings_writer_preserves_bom_and_crlf(self):\n        from games.bannerlord.settings_data import save_mcm_defaults\n        with tempfile.TemporaryDirectory() as name:\n            root=Path(name);(root/"src").mkdir();path=root/"src/LexerSkillTweaksSettings.cs"\n            path.write_bytes(b"\\xef\\xbb\\xbf"+TEXT.replace("\\n","\\r\\n").encode())\n            save_mcm_defaults(root,[{"property":"Native","value":True}])\n            raw=path.read_bytes();self.assertTrue(raw.startswith(b"\\xef\\xbb\\xbf"));self.assertNotIn(b"\\n",raw[3:].replace(b"\\r\\n",b""));self.assertIn(b"private bool _native = true;",raw)\n\n'''
if text.count(marker) != 1: raise SystemExit("settings fidelity test insertion point changed")
settings_tests.write_text(text.replace(marker, addition + marker, 1), encoding="utf-8")
