"use strict";
const {el,columnList,detailPanel,detailSection,detailField,readonlyField,recordId,infoHelp,pagedListDetail,panelLayout,infoIcon}=LexeditorUI;
const $=selector=>document.querySelector(selector);
const TABS=[{id:"text",label:"Text"},{id:"scenes",label:"Areas"},{id:"exits",label:"Area Exits"},{id:"treasure",label:"Treasure"}];
const FACING=[[0,"Up"],[1,"Down"],[2,"Left"],[3,"Right"]];
const KINDS=[["weapon","Weapon"],["armor","Armor"],["helmet","Helmet"],["accessory","Accessory"],["consumable","Consumable"],["item","Item"],["gold","Gold"]];
const state={tab:"text",source:"mine",busy:true,error:"",dashboard:null,dataMap:{rows:[]},changes:[],language:"en",textFiles:[],textPath:"",text:{rows:[]},scenes:{rows:[]},exits:{rows:[]},treasure:{rows:[]},dirty:new Map(),selected:{text:null,scenes:null,exits:null,treasure:null},page:{text:0,scenes:0,exits:0,treasure:0},pageSize:{text:18,scenes:18,exits:18,treasure:18},query:{text:"",scenes:"",exits:"",treasure:""},sort:{text:{key:"key",dir:1},scenes:{key:"id",dir:1},exits:{key:"sceneId",dir:1},treasure:{key:"sceneId",dir:1}},mapPage:0,mapQuery:"",mapStatus:"",mapSort:["filename",1],exportResult:null};
async function api(path,body){const response=await fetch(path,body===undefined?{}:{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const value=await response.json();if(!response.ok)throw new Error(value.error||`Request failed (${response.status})`);return value}
function setToolbar(...nodes){$("#toolbar").replaceChildren(...nodes.filter(Boolean))}
function readonly(){return state.busy||state.source!=="mine"}
function dirtyCount(){return state.dirty.size}
function pendingChanges(){return [...state.dirty.values()].flatMap(entry=>Object.entries(entry.values).map(([field,after])=>({label:`${entry.tab} / ${entry.token} / ${field}`,before:entry.original[field],after})))}
function remember(tab,row,values){const key=`${tab}:${row.token}`,entry=state.dirty.get(key)||{tab,token:row.token,original:{},values:{}};for(const [field,value] of Object.entries(values)){if(!(field in entry.original))entry.original[field]=row[field];entry.values[field]=value;row[field]=value;if(entry.original[field]===value){delete entry.values[field];delete entry.original[field]}}if(Object.keys(entry.values).length)state.dirty.set(key,entry);else state.dirty.delete(key);shell.refresh()}
function rows(tab){if(tab==="text")return state.text.rows||[];if(tab==="scenes")return state.scenes.rows||[];if(tab==="exits")return state.exits.rows||[];return state.treasure.rows||[]}
function sorted(tab){const q=state.query[tab].toLocaleLowerCase(),{key,dir}=state.sort[tab];return [...rows(tab)].filter(row=>!q||JSON.stringify(row).toLocaleLowerCase().includes(q)).sort((a,b)=>{const left=a[key],right=b[key],r=typeof left==="string"?String(left).localeCompare(String(right)):Number(left)-Number(right);return r*dir})}
function sort(tab,key){const active=state.sort[tab];state.sort[tab]=active.key===key?{key,dir:-active.dir}:{key,dir:1};state.page[tab]=0;render()}
function numberField(tab,row,key,min,max,help){return {dataType:"INT",min,max,help:help?infoHelp(help):null,control:el("input",{type:"number",min,max,step:1,value:row[key],disabled:readonly(),oninput:event=>{if(event.target.value!=="")remember(tab,row,{[key]:Number(event.target.value)})}})}}
function boolField(tab,row,key,help){return {dataType:"BOOL",help:help?infoHelp(help):null,control:el("input",{type:"checkbox",checked:!!row[key],disabled:readonly(),onchange:event=>remember(tab,row,{[key]:event.target.checked})})}}
function selectField(tab,row,key,choices,help){const control=el("select",{disabled:readonly(),onchange:event=>{const raw=event.target.value,value=choices.some(([v])=>typeof v==="number")?Number(raw):raw;remember(tab,row,{[key]:value});render()}},...choices.map(([value,label])=>{const option=el("option",{value},label);option.selected=String(row[key])===String(value);return option}));return {dataType:"ENUM",help:help?infoHelp(help):null,control}}
function master(tab,view,columns){return columnList({rows:view.rows,key:row=>row.token,selected:view.selected,select:view.select,columns,sortState:state.sort[tab],sort:key=>sort(tab,key),class:"ct-table",refresh:render})}
function records(tab,columns,detail,noun){const filtered=sorted(tab);if(!filtered.length)return el("div",{class:"ct-empty"},`No ${noun} match this view.`);if(!filtered.some(row=>row.token===state.selected[tab]))state.selected[tab]=filtered[0].token;return pagedListDetail({rows:filtered,key:row=>row.token,selected:state.selected[tab],page:state.page[tab],pageSize:state.pageSize[tab],noun,className:"ct-layout",splitKey:`chrono-${tab}`,rowsKey:`chrono-${tab}`,defaultSplit:48,minLeft:320,minRight:380,search:{key:`chrono-${tab}`,value:state.query[tab],label:`Search ${noun}`,change:value=>{state.query[tab]=value;state.page[tab]=0;render()}},sync:next=>{state.page[tab]=next.page;state.pageSize[tab]=next.pageSize;if(next.selected!==null)state.selected[tab]=next.selected},change:next=>{state.page[tab]=next.page;state.pageSize[tab]=next.pageSize;if(next.selected!==null)state.selected[tab]=next.selected;render()},master:view=>master(tab,view,columns),detail})}
function textDetail(row){const control=el("textarea",{class:"ct-long-text",value:row.text,disabled:readonly(),oninput:event=>remember("text",row,{text:event.target.value})});return detailPanel({className:"ct-detail",title:row.key,meta:state.text.path||"",body:[detailSection({title:"MESSAGE",body:[detailField({label:"TEXT",dataType:"STRING",control,help:infoHelp("Text displayed for this keyed Steam message. Its record key and original line ending are preserved on save.")}),detailField({label:"KEY",control:readonlyField(row.key)}),detailField({label:"SOURCE FILE",control:readonlyField(state.text.path||"")})]})]})}
function textView(){return records("text",[{key:"key",label:"Key",sortable:true},{key:"text",label:"Text",sortable:true}],textDetail,"messages")}
function sceneDetail(row){return detailPanel({className:"ct-detail",title:row.name,identity:recordId(row.id),meta:row.path,body:[
  detailSection({title:"AREA",body:[
    detailField({label:"MUSIC",...numberField("scenes",row,"musicIndex",0,65535,"Music track reference loaded with this area.")}),
    detailField({label:"MAP",...numberField("scenes",row,"mapIndex",0,65535,"Map layout reference used by this area.")}),
    detailField({label:"EVENT SCRIPT",...numberField("scenes",row,"scriptIndex",0,65535,"Field event script reference used when this area loads.")}),
  ]}),
  detailSection({title:"GRAPHICS",body:[
    detailField({label:"L1/L2 TILESET",...numberField("scenes",row,"layer12TilesetIndex",0,65535,"Graphics-set reference for the first two map layers.")}),
    detailField({label:"L1/L2 ASSEMBLY",...numberField("scenes",row,"layer12AssemblyIndex",0,65535,"Tile-assembly reference for the first two map layers.")}),
    detailField({label:"L3 TILESET",...numberField("scenes",row,"layer3TilesetIndex",0,65535,"Graphics-set reference for the third map layer.")}),
    detailField({label:"PALETTE",...numberField("scenes",row,"paletteIndex",0,65535,"Color-palette reference used by this area.")}),
    detailField({label:"PALETTE ANIMATION",...numberField("scenes",row,"paletteAnimationIndex",0,65535,"Palette-animation set selected by this area.")}),
    detailField({label:"CHIP ANIMATION",...numberField("scenes",row,"chipAnimationIndex",0,65535,"Animated-tile descriptor selected by this area.")}),
  ]}),
  detailSection({title:"CAMERA",body:[
    detailField({label:"FULL MAP",...boolField("scenes",row,"cameraUnbounded","Steam uses 0x80 in the left camera byte to disable the stored scroll rectangle and allow the full map.")}),
    detailField({label:"LEFT",...numberField("scenes",row,"scrollLeft",0,255,"Left edge of the stored camera rectangle, in map tiles. FULL MAP overrides this with the Steam 0x80 sentinel on save.")}),
    detailField({label:"TOP",...numberField("scenes",row,"scrollTop",0,255,"Top edge of the stored camera rectangle, in map tiles.")}),
    detailField({label:"RIGHT",...numberField("scenes",row,"scrollRight",0,255,"Stored right camera edge. The runtime interprets the normal bounded value as inclusive.")}),
    detailField({label:"BOTTOM",...numberField("scenes",row,"scrollBottom",0,255,"Stored bottom camera edge. The runtime interprets the normal bounded value as inclusive.")}),
  ]}),
  detailSection({title:"PRESERVED",body:[
    detailField({label:"PC WORD",control:readonlyField(`0x${row.unknownWord.toString(16).padStart(4,"0").toUpperCase()}`),help:infoHelp("This PC-only word has no established gameplay meaning in the audited source and is preserved unchanged.")}),
    detailField({label:"TRAILING BYTES",control:readonlyField(String(row.trailingBytes)),help:infoHelp("Any bytes after the documented 24-byte Steam header are preserved unchanged.")}),
  ]}),
]})}
function scenesView(){return records("scenes",[
  {key:"id",label:"ID",numberedId:true,sortable:true},
  {key:"name",label:"Area",sortable:true},
  {key:"musicIndex",label:"Music",numeric:true,sortable:true},
  {key:"mapIndex",label:"Map",numeric:true,sortable:true},
  {key:"scriptIndex",label:"Script",numeric:true,sortable:true},
],sceneDetail,"areas")}
function exitDetail(row){return detailPanel({className:"ct-detail",title:`Exit ${row.exitId}`,identity:recordId(row.sceneId),meta:`Scene ${row.sceneId}`,body:[detailSection({title:"TRIGGER",body:[detailField({label:"X TILE",...numberField("exits",row,"xTile",0,255,"Start tile of the exit trigger.")}),detailField({label:"Y TILE",...numberField("exits",row,"yTile",0,255,"Start tile of the exit trigger.")}),detailField({label:"LENGTH",...numberField("exits",row,"lengthTiles",1,128,"Number of tiles spanned by the trigger.")}),detailField({label:"ORIENTATION",...selectField("exits",row,"orientation",[["horizontal","Horizontal"],["vertical","Vertical"]],"Direction the trigger extends from its start tile.")})]}),detailSection({title:"DESTINATION",body:[detailField({label:"LOCATION ID",...numberField("exits",row,"destinationId",0,511,"Scene IDs are direct. IDs 496–511 address world maps.")}),detailField({label:"LOCATION TYPE",control:readonlyField(row.destinationId>=496?"World map":"Scene")}),detailField({label:"X TILE",...numberField("exits",row,"targetX",0,255,"Stored destination X coordinate.")}),detailField({label:"Y TILE",...numberField("exits",row,"targetY",0,255,"Stored destination Y coordinate.")}),detailField({label:"FACING",...selectField("exits",row,"facing",FACING,"Direction the party faces after arrival.")}),detailField({label:"HALF TILE LEFT",...boolField("exits",row,"halfTileLeft","Offsets the destination eight pixels left.")}),detailField({label:"HALF TILE UP",...boolField("exits",row,"halfTileUp","Offsets the destination eight pixels upward.")}),detailField({label:"PRESERVED BITS",control:readonlyField(`0x${row.unknownFacingBits.toString(16).padStart(2,"0").toUpperCase()}`),help:infoHelp("Unmodelled upper flag bits are preserved byte-for-byte.")})]})]})}
function exitsView(){return records("exits",[{key:"sceneId",label:"Scene",numberedId:true,sortable:true},{key:"exitId",label:"Exit",numberedId:true,sortable:true},{key:"destinationId",label:"Destination",numeric:true,sortable:true},{key:"orientation",label:"Shape",sortable:true}],exitDetail,"exits")}
function treasureDetail(row){if(row.alias)return detailPanel({className:"ct-detail",title:`Treasure ${row.treasureId}`,identity:recordId(row.sceneId),meta:`Scene ${row.sceneId}`,body:[detailSection({title:"ALIAS",body:[detailField({label:"OTHER SCENE",control:readonlyField(String(row.aliasScene)),help:infoHelp("A 0,0 position redirects treasure lookup to another scene. Alias records remain read-only.")}),detailField({label:"PRESERVED WORD",control:readonlyField(`0x${row.trailingWord.toString(16).padStart(4,"0").toUpperCase()}`)})]})]});if(!row.editable)return detailPanel({className:"ct-detail",title:`Treasure ${row.treasureId}`,identity:recordId(row.sceneId),meta:`Scene ${row.sceneId}`,body:[el("p",{class:"ct-info-note"},"This record uses an unknown contents encoding and is preserved read-only.")]});const contents=row.kind==="gold"?[detailField({label:"GOLD",...numberField("treasure",row,"gold",0,65534,"Steam stores treasure gold in increments of two.")})]:[detailField({label:"ITEM INDEX",...numberField("treasure",row,"localIndex",0,511,"Index within the selected Steam item category.")}),detailField({label:"RESOLVED ITEM",control:readonlyField(row.itemName||"Name unavailable")})];return detailPanel({className:"ct-detail",title:`Treasure ${row.treasureId}`,identity:recordId(row.sceneId),meta:`Scene ${row.sceneId}`,body:[detailSection({title:"POSITION",body:[detailField({label:"X TILE",...numberField("treasure",row,"xTile",0,255,"Chest X tile. 0,0 together is reserved for an alias.")}),detailField({label:"Y TILE",...numberField("treasure",row,"yTile",0,255,"Chest Y tile. 0,0 together is reserved for an alias.")})]}),detailSection({title:"CONTENTS",body:[detailField({label:"TYPE",...selectField("treasure",row,"kind",KINDS,"Known Steam treasure encoding family.")}),...contents,detailField({label:"PRESERVED WORD",control:readonlyField(`0x${row.trailingWord.toString(16).padStart(4,"0").toUpperCase()}`),help:infoHelp("The final PC treasure word has no established meaning here and is never rewritten.")})]})]})}
function treasureView(){return records("treasure",[{key:"sceneId",label:"Scene",numberedId:true,sortable:true},{key:"treasureId",label:"Chest",numberedId:true,sortable:true},{key:"kind",label:"Contents",sortable:true},{key:"itemName",label:"Item",sortable:true}],treasureDetail,"treasure records")}
function infoView(){const actions=el("div",{class:"ct-actions"},el("button",{type:"button",disabled:state.busy||dirtyCount()>0||state.source!=="mine",onclick:exportCtp},"Export CTP"),el("button",{type:"button",disabled:state.busy,onclick:()=>refreshInfo(true)},"Refresh"));return panelLayout([detailPanel({className:"ct-detail lex-information-panel",icon:infoIcon(),title:"Chrono Trigger",meta:"Steam replacement plugin",body:[detailSection({title:"GAME",body:[detailField({label:"INSTALL",control:readonlyField(state.dashboard?.game?.root||"")}),detailField({label:"ARCHIVE",control:readonlyField(state.dashboard?.game?.archive||"")}),detailField({label:"RESOURCES",control:readonlyField(String(state.dashboard?.game?.resourceCount??0))})]}),detailSection({title:"PROJECT",body:[detailField({label:"FOLDER",control:readonlyField(state.dashboard?.project?.root||"")}),detailField({label:"CHANGED FILES",control:readonlyField(String(state.changes.length))}),detailField({label:"ACTIONS",control:actions}),...(state.exportResult?[detailField({label:"LAST EXPORT",control:readonlyField(state.exportResult.path)})]:[])]}),LexeditorUI.modLoaderSection({loader:"Lexeditor exports standard Chrono Trigger .ctp ZIP packages. No runtime loader is bundled by this plugin.",output:"Each CTP contains only changed Game/... and Localize/... resources at resources.bin-relative paths. The installed resources.bin remains unchanged.",order:"Runtime load order belongs to the external loader. Lexeditor exports one project and does not claim semantic merging between separate CTP mods.",safety:"Project writes stay outside the game folder; export never repacks or overwrites resources.bin.",removal:"Remove the exported CTP from the loader's mod location, or revert the project override in Lexeditor."}),LexeditorUI.creditsPanel("chrono-trigger")]})],"ct-layout",{layoutKey:"chrono-info",defaultSizes:[100]})}
function dataMapView(){const view=LexeditorUI.dataMap({rows:state.dataMap.rows||[],query:state.mapQuery,status:state.mapStatus,page:state.mapPage,sort:state.mapSort,pageSize:100,open:row=>row.target&&navigate(row.target),changeQuery:value=>{state.mapQuery=value;state.mapPage=0;render()},changeStatus:value=>{state.mapStatus=value;state.mapPage=0;render()},changePage:value=>{state.mapPage=value;render()},changeSort:key=>{const [active,dir]=state.mapSort;state.mapSort=[key,active===key?-dir:1];render()}});state.mapPage=view.page;setToolbar(view.controls);return view.content}
function textToolbar(){const language=el("select",{onchange:async event=>{state.language=event.target.value;await loadTextFiles(true)}},...(state.dashboard?.languages||[]).map(value=>{const option=el("option",{value},value);option.selected=value===state.language;return option}));const file=el("select",{onchange:async event=>{state.textPath=event.target.value;await loadText()}},...state.textFiles.map(value=>{const option=el("option",{value},value.split("/").pop());option.selected=value===state.textPath;return option}));return [el("label",{},"Language",language),el("label",{},"File",file)]}
function render(){if(state.busy){setToolbar();$("#main").replaceChildren(el("div",{class:"ct-loading",role:"status"},"Loading Chrono Trigger data…"));shell?.refresh?.();return}if(state.error){setToolbar();$("#main").replaceChildren(el("div",{class:"ct-error",role:"alert"},state.error));shell?.refresh?.();return}if(state.tab==="info"){setToolbar();$("#main").replaceChildren(infoView())}else if(state.tab==="datamap"){$("#main").replaceChildren(dataMapView())}else if(state.tab==="text"){setToolbar(...textToolbar());$("#main").replaceChildren(textView())}else if(state.tab==="scenes"){setToolbar();$("#main").replaceChildren(scenesView())}else if(state.tab==="exits"){setToolbar();$("#main").replaceChildren(exitsView())}else{setToolbar();$("#main").replaceChildren(treasureView())}shell?.refresh?.()}
async function loadTextFiles(reset=false){const result=await api(`/api/text-files?language=${encodeURIComponent(state.language)}`);state.textFiles=result.rows;if(reset||!state.textFiles.includes(state.textPath))state.textPath=state.textFiles[0]||"";await loadText(false)}
async function loadText(draw=true){state.text=state.textPath?await api(`/api/messages?path=${encodeURIComponent(state.textPath)}&source=${state.source}`):{rows:[]};state.selected.text=state.text.rows[0]?.token??null;if(draw){state.busy=false;render()}}
async function loadTab(){state.busy=true;state.error="";render();try{if(state.tab==="text")await loadTextFiles(false);else if(state.tab==="scenes"){state.scenes=await api(`/api/scenes?source=${state.source}&language=${encodeURIComponent(state.language)}`);state.selected.scenes=state.scenes.rows[0]?.token??null}else if(state.tab==="exits"){state.exits=await api(`/api/exits?source=${state.source}`);state.selected.exits=state.exits.rows[0]?.token??null}else if(state.tab==="treasure"){state.treasure=await api(`/api/treasure?source=${state.source}&language=${encodeURIComponent(state.language)}`);state.selected.treasure=state.treasure.rows[0]?.token??null}else if(state.tab==="info")await refreshInfo(false)}catch(error){state.error=error.message}finally{state.busy=false;render()}}
async function navigate(tab){if(tab===state.tab)return;if(dirtyCount()&&!await LexeditorUI.confirmAction({title:"Unsaved changes",message:"Discard unsaved Chrono Trigger edits before changing pages?",confirmLabel:"Discard",cancelLabel:"Stay"}))return;state.dirty.clear();state.tab=tab;await loadTab()}
async function save(){if(readonly()||!dirtyCount())return;state.busy=true;render();try{const edits=[...state.dirty.values()].filter(entry=>entry.tab===state.tab).map(entry=>({token:entry.token,values:entry.values}));if(state.tab==="text"){const textEdits=edits.map(entry=>{const row=state.text.rows.find(row=>row.token===entry.token);return {line:row.line,key:row.key,text:entry.values.text}});state.text=await api("/api/messages/save",{path:state.text.path,sha256:state.text.sha256,edits:textEdits})}else if(state.tab==="scenes"){for(const entry of edits){const row=state.scenes.rows.find(row=>row.token===entry.token);const saved=await api("/api/scenes/save",{id:row.id,sha256:row.sha256,language:state.language,values:entry.values});Object.assign(row,saved)}}else if(state.tab==="exits")state.exits=await api("/api/exits/save",{dataSha256:state.exits.dataSha256,offsetSha256:state.exits.offsetSha256,edits});else state.treasure=await api("/api/treasure/save",{dataSha256:state.treasure.dataSha256,offsetSha256:state.treasure.offsetSha256,language:state.language,edits});state.dirty.clear();await refreshInfo(false)}catch(error){state.error=error.message;throw error}finally{state.busy=false;render()}}
async function discard(){state.dirty.clear();await loadTab()}
async function switchSource(value){if(dirtyCount())await discard();state.source=String(value)==="vanilla"?"vanilla":"mine";await loadTab()}
async function refreshInfo(draw=true){const [dashboard,changes,map]=await Promise.all([api("/api/dashboard"),api("/api/changes"),api("/api/datamap")]);state.dashboard=dashboard;state.changes=changes.rows;state.dataMap=map;if(draw){state.busy=false;render()}}
async function exportCtp(){state.busy=true;render();try{state.exportResult=await api("/api/export",{});await refreshInfo(false)}catch(error){state.error=error.message}finally{state.busy=false;render()}}
const shell=LexeditorUI.mountShell({host:"#lexeditor-shell",brand:"LEXEDITOR",plugin:{id:"chrono-trigger",name:"Chrono Trigger",themeName:"chrono-trigger",theme:{accent:"#d3a348","accent-text":"#1c1608"}},tabs:TABS,activeTab:()=>state.tab,navigate,help:()=>navigate("datamap"),helpActive:()=>state.tab==="datamap",helpTitle:"Open Chrono Trigger Data Map",info:()=>navigate("info"),infoActive:()=>state.tab==="info",infoTitle:"Open Chrono Trigger plugin information",projectSources:()=>[{key:"vanilla",label:"Vanilla",path:state.dashboard?.game?.archive||"Installed resources.bin"}],projectActiveSource:()=>state.source,selectProjectSource:switchSource,pendingChanges,dirtyCount,readonly,save,discard});
Promise.all([api("/api/dashboard"),api("/api/datamap"),api("/api/changes")]).then(async([dashboard,map,changes])=>{state.dashboard=dashboard;state.dataMap=map;state.changes=changes.rows;state.language=dashboard.defaultLanguage||"en";await loadTextFiles(false);state.busy=false;render();LexeditorUI.finishPluginLoading()}).catch(error=>{state.busy=false;state.error=error.message;render();LexeditorUI.finishPluginLoading()});
